/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigServicePutConfigBody model module.
 * @module model/ConfigServicePutConfigBody
 * @version 4.0
 */
class ConfigServicePutConfigBody {
    /**
     * Constructs a new <code>ConfigServicePutConfigBody</code>.
     * @alias module:model/ConfigServicePutConfigBody
     */
    constructor() { 
        
        ConfigServicePutConfigBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigServicePutConfigBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigServicePutConfigBody} obj Optional instance to populate.
     * @return {module:model/ConfigServicePutConfigBody} The populated <code>ConfigServicePutConfigBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigServicePutConfigBody();

            if (data.hasOwnProperty('Data')) {
                obj['Data'] = ApiClient.convertToType(data['Data'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigServicePutConfigBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigServicePutConfigBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Data'] && !(typeof data['Data'] === 'string' || data['Data'] instanceof String)) {
            throw new Error("Expected the field `Data` to be a primitive type in the JSON string but got " + data['Data']);
        }

        return true;
    }


}



/**
 * @member {String} Data
 */
ConfigServicePutConfigBody.prototype['Data'] = undefined;






export default ConfigServicePutConfigBody;

