/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EncryptionExport model module.
 * @module model/EncryptionExport
 * @version 4.0
 */
class EncryptionExport {
    /**
     * Constructs a new <code>EncryptionExport</code>.
     * @alias module:model/EncryptionExport
     */
    constructor() { 
        
        EncryptionExport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EncryptionExport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EncryptionExport} obj Optional instance to populate.
     * @return {module:model/EncryptionExport} The populated <code>EncryptionExport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EncryptionExport();

            if (data.hasOwnProperty('By')) {
                obj['By'] = ApiClient.convertToType(data['By'], 'String');
            }
            if (data.hasOwnProperty('Date')) {
                obj['Date'] = ApiClient.convertToType(data['Date'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EncryptionExport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EncryptionExport</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['By'] && !(typeof data['By'] === 'string' || data['By'] instanceof String)) {
            throw new Error("Expected the field `By` to be a primitive type in the JSON string but got " + data['By']);
        }

        return true;
    }


}



/**
 * @member {String} By
 */
EncryptionExport.prototype['By'] = undefined;

/**
 * @member {Number} Date
 */
EncryptionExport.prototype['Date'] = undefined;






export default EncryptionExport;

