/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EncryptionExport from './EncryptionExport';
import EncryptionImport from './EncryptionImport';

/**
 * The EncryptionKeyInfo model module.
 * @module model/EncryptionKeyInfo
 * @version 4.0
 */
class EncryptionKeyInfo {
    /**
     * Constructs a new <code>EncryptionKeyInfo</code>.
     * @alias module:model/EncryptionKeyInfo
     */
    constructor() { 
        
        EncryptionKeyInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EncryptionKeyInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EncryptionKeyInfo} obj Optional instance to populate.
     * @return {module:model/EncryptionKeyInfo} The populated <code>EncryptionKeyInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EncryptionKeyInfo();

            if (data.hasOwnProperty('Exports')) {
                obj['Exports'] = ApiClient.convertToType(data['Exports'], [EncryptionExport]);
            }
            if (data.hasOwnProperty('Imports')) {
                obj['Imports'] = ApiClient.convertToType(data['Imports'], [EncryptionImport]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EncryptionKeyInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EncryptionKeyInfo</code>.
     */
    static validateJSON(data) {
        if (data['Exports']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Exports'])) {
                throw new Error("Expected the field `Exports` to be an array in the JSON data but got " + data['Exports']);
            }
            // validate the optional field `Exports` (array)
            for (const item of data['Exports']) {
                EncryptionExport.validateJSON(item);
            };
        }
        if (data['Imports']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Imports'])) {
                throw new Error("Expected the field `Imports` to be an array in the JSON data but got " + data['Imports']);
            }
            // validate the optional field `Imports` (array)
            for (const item of data['Imports']) {
                EncryptionImport.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/EncryptionExport>} Exports
 */
EncryptionKeyInfo.prototype['Exports'] = undefined;

/**
 * @member {Array.<module:model/EncryptionImport>} Imports
 */
EncryptionKeyInfo.prototype['Imports'] = undefined;






export default EncryptionKeyInfo;

