/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmACLAction from './IdmACLAction';

/**
 * The IdmACL model module.
 * @module model/IdmACL
 * @version 4.0
 */
class IdmACL {
    /**
     * Constructs a new <code>IdmACL</code>.
     * ACL are the basic flags that can be put anywhere in the tree to provide some specific rights to a given role. The context of how they apply can be fine-tuned by workspace.
     * @alias module:model/IdmACL
     */
    constructor() { 
        
        IdmACL.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmACL</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmACL} obj Optional instance to populate.
     * @return {module:model/IdmACL} The populated <code>IdmACL</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmACL();

            if (data.hasOwnProperty('Action')) {
                obj['Action'] = IdmACLAction.constructFromObject(data['Action']);
            }
            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
            }
            if (data.hasOwnProperty('NodeID')) {
                obj['NodeID'] = ApiClient.convertToType(data['NodeID'], 'String');
            }
            if (data.hasOwnProperty('RoleID')) {
                obj['RoleID'] = ApiClient.convertToType(data['RoleID'], 'String');
            }
            if (data.hasOwnProperty('WorkspaceID')) {
                obj['WorkspaceID'] = ApiClient.convertToType(data['WorkspaceID'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmACL</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmACL</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Action`
        if (data['Action']) { // data not null
          IdmACLAction.validateJSON(data['Action']);
        }
        // ensure the json data is a string
        if (data['ID'] && !(typeof data['ID'] === 'string' || data['ID'] instanceof String)) {
            throw new Error("Expected the field `ID` to be a primitive type in the JSON string but got " + data['ID']);
        }
        // ensure the json data is a string
        if (data['NodeID'] && !(typeof data['NodeID'] === 'string' || data['NodeID'] instanceof String)) {
            throw new Error("Expected the field `NodeID` to be a primitive type in the JSON string but got " + data['NodeID']);
        }
        // ensure the json data is a string
        if (data['RoleID'] && !(typeof data['RoleID'] === 'string' || data['RoleID'] instanceof String)) {
            throw new Error("Expected the field `RoleID` to be a primitive type in the JSON string but got " + data['RoleID']);
        }
        // ensure the json data is a string
        if (data['WorkspaceID'] && !(typeof data['WorkspaceID'] === 'string' || data['WorkspaceID'] instanceof String)) {
            throw new Error("Expected the field `WorkspaceID` to be a primitive type in the JSON string but got " + data['WorkspaceID']);
        }

        return true;
    }


}



/**
 * @member {module:model/IdmACLAction} Action
 */
IdmACL.prototype['Action'] = undefined;

/**
 * @member {String} ID
 */
IdmACL.prototype['ID'] = undefined;

/**
 * @member {String} NodeID
 */
IdmACL.prototype['NodeID'] = undefined;

/**
 * @member {String} RoleID
 */
IdmACL.prototype['RoleID'] = undefined;

/**
 * @member {String} WorkspaceID
 */
IdmACL.prototype['WorkspaceID'] = undefined;






export default IdmACL;

