/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmACLAction from './IdmACLAction';

/**
 * The IdmACLSingleQuery model module.
 * @module model/IdmACLSingleQuery
 * @version 4.0
 */
class IdmACLSingleQuery {
    /**
     * Constructs a new <code>IdmACLSingleQuery</code>.
     * @alias module:model/IdmACLSingleQuery
     */
    constructor() { 
        
        IdmACLSingleQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmACLSingleQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmACLSingleQuery} obj Optional instance to populate.
     * @return {module:model/IdmACLSingleQuery} The populated <code>IdmACLSingleQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmACLSingleQuery();

            if (data.hasOwnProperty('Actions')) {
                obj['Actions'] = ApiClient.convertToType(data['Actions'], [IdmACLAction]);
            }
            if (data.hasOwnProperty('NodeIDs')) {
                obj['NodeIDs'] = ApiClient.convertToType(data['NodeIDs'], ['String']);
            }
            if (data.hasOwnProperty('RoleIDs')) {
                obj['RoleIDs'] = ApiClient.convertToType(data['RoleIDs'], ['String']);
            }
            if (data.hasOwnProperty('WorkspaceIDs')) {
                obj['WorkspaceIDs'] = ApiClient.convertToType(data['WorkspaceIDs'], ['String']);
            }
            if (data.hasOwnProperty('not')) {
                obj['not'] = ApiClient.convertToType(data['not'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/IdmACLAction>} Actions
 */
IdmACLSingleQuery.prototype['Actions'] = undefined;

/**
 * @member {Array.<String>} NodeIDs
 */
IdmACLSingleQuery.prototype['NodeIDs'] = undefined;

/**
 * @member {Array.<String>} RoleIDs
 */
IdmACLSingleQuery.prototype['RoleIDs'] = undefined;

/**
 * @member {Array.<String>} WorkspaceIDs
 */
IdmACLSingleQuery.prototype['WorkspaceIDs'] = undefined;

/**
 * @member {Boolean} not
 */
IdmACLSingleQuery.prototype['not'] = undefined;






export default IdmACLSingleQuery;

