/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmEntityValue from './IdmEntityValue';

/**
 * The IdmCreateEntityValueResponse model module.
 * @module model/IdmCreateEntityValueResponse
 * @version 4.0
 */
class IdmCreateEntityValueResponse {
    /**
     * Constructs a new <code>IdmCreateEntityValueResponse</code>.
     * @alias module:model/IdmCreateEntityValueResponse
     */
    constructor() { 
        
        IdmCreateEntityValueResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmCreateEntityValueResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmCreateEntityValueResponse} obj Optional instance to populate.
     * @return {module:model/IdmCreateEntityValueResponse} The populated <code>IdmCreateEntityValueResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmCreateEntityValueResponse();

            if (data.hasOwnProperty('EntityValue')) {
                obj['EntityValue'] = ApiClient.convertToType(data['EntityValue'], [IdmEntityValue]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmCreateEntityValueResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmCreateEntityValueResponse</code>.
     */
    static validateJSON(data) {
        if (data['EntityValue']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['EntityValue'])) {
                throw new Error("Expected the field `EntityValue` to be an array in the JSON data but got " + data['EntityValue']);
            }
            // validate the optional field `EntityValue` (array)
            for (const item of data['EntityValue']) {
                IdmEntityValue.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/IdmEntityValue>} EntityValue
 */
IdmCreateEntityValueResponse.prototype['EntityValue'] = undefined;






export default IdmCreateEntityValueResponse;

