/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdmDeleteEntityValueResponse model module.
 * @module model/IdmDeleteEntityValueResponse
 * @version 4.0
 */
class IdmDeleteEntityValueResponse {
    /**
     * Constructs a new <code>IdmDeleteEntityValueResponse</code>.
     * @alias module:model/IdmDeleteEntityValueResponse
     */
    constructor() { 
        
        IdmDeleteEntityValueResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmDeleteEntityValueResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmDeleteEntityValueResponse} obj Optional instance to populate.
     * @return {module:model/IdmDeleteEntityValueResponse} The populated <code>IdmDeleteEntityValueResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmDeleteEntityValueResponse();

            if (data.hasOwnProperty('RowsDeleted')) {
                obj['RowsDeleted'] = ApiClient.convertToType(data['RowsDeleted'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmDeleteEntityValueResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmDeleteEntityValueResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['RowsDeleted'] && !(typeof data['RowsDeleted'] === 'string' || data['RowsDeleted'] instanceof String)) {
            throw new Error("Expected the field `RowsDeleted` to be a primitive type in the JSON string but got " + data['RowsDeleted']);
        }

        return true;
    }


}



/**
 * @member {String} RowsDeleted
 */
IdmDeleteEntityValueResponse.prototype['RowsDeleted'] = undefined;






export default IdmDeleteEntityValueResponse;

