/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdmPolicyAction model module.
 * @module model/IdmPolicyAction
 * @version 4.0
 */
class IdmPolicyAction {
    /**
     * Constructs a new <code>IdmPolicyAction</code>.
     * @alias module:model/IdmPolicyAction
     */
    constructor() { 
        
        IdmPolicyAction.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmPolicyAction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmPolicyAction} obj Optional instance to populate.
     * @return {module:model/IdmPolicyAction} The populated <code>IdmPolicyAction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmPolicyAction();

            if (data.hasOwnProperty('Compiled')) {
                obj['Compiled'] = ApiClient.convertToType(data['Compiled'], 'String');
            }
            if (data.hasOwnProperty('HasRegex')) {
                obj['HasRegex'] = ApiClient.convertToType(data['HasRegex'], 'Boolean');
            }
            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
            }
            if (data.hasOwnProperty('Template')) {
                obj['Template'] = ApiClient.convertToType(data['Template'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmPolicyAction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmPolicyAction</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Compiled'] && !(typeof data['Compiled'] === 'string' || data['Compiled'] instanceof String)) {
            throw new Error("Expected the field `Compiled` to be a primitive type in the JSON string but got " + data['Compiled']);
        }
        // ensure the json data is a string
        if (data['ID'] && !(typeof data['ID'] === 'string' || data['ID'] instanceof String)) {
            throw new Error("Expected the field `ID` to be a primitive type in the JSON string but got " + data['ID']);
        }
        // ensure the json data is a string
        if (data['Template'] && !(typeof data['Template'] === 'string' || data['Template'] instanceof String)) {
            throw new Error("Expected the field `Template` to be a primitive type in the JSON string but got " + data['Template']);
        }

        return true;
    }


}



/**
 * @member {String} Compiled
 */
IdmPolicyAction.prototype['Compiled'] = undefined;

/**
 * @member {Boolean} HasRegex
 */
IdmPolicyAction.prototype['HasRegex'] = undefined;

/**
 * @member {String} ID
 */
IdmPolicyAction.prototype['ID'] = undefined;

/**
 * @member {String} Template
 */
IdmPolicyAction.prototype['Template'] = undefined;






export default IdmPolicyAction;

