/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceResourcePolicy from './ServiceResourcePolicy';

/**
 * The IdmUserMetaNamespace model module.
 * @module model/IdmUserMetaNamespace
 * @version 4.0
 */
class IdmUserMetaNamespace {
    /**
     * Constructs a new <code>IdmUserMetaNamespace</code>.
     * @alias module:model/IdmUserMetaNamespace
     */
    constructor() { 
        
        IdmUserMetaNamespace.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmUserMetaNamespace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmUserMetaNamespace} obj Optional instance to populate.
     * @return {module:model/IdmUserMetaNamespace} The populated <code>IdmUserMetaNamespace</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmUserMetaNamespace();

            if (data.hasOwnProperty('Indexable')) {
                obj['Indexable'] = ApiClient.convertToType(data['Indexable'], 'Boolean');
            }
            if (data.hasOwnProperty('JsonDefinition')) {
                obj['JsonDefinition'] = ApiClient.convertToType(data['JsonDefinition'], 'String');
            }
            if (data.hasOwnProperty('Label')) {
                obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
            }
            if (data.hasOwnProperty('Namespace')) {
                obj['Namespace'] = ApiClient.convertToType(data['Namespace'], 'String');
            }
            if (data.hasOwnProperty('Order')) {
                obj['Order'] = ApiClient.convertToType(data['Order'], 'Number');
            }
            if (data.hasOwnProperty('Policies')) {
                obj['Policies'] = ApiClient.convertToType(data['Policies'], [ServiceResourcePolicy]);
            }
            if (data.hasOwnProperty('PoliciesContextEditable')) {
                obj['PoliciesContextEditable'] = ApiClient.convertToType(data['PoliciesContextEditable'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} Indexable
 */
IdmUserMetaNamespace.prototype['Indexable'] = undefined;

/**
 * @member {String} JsonDefinition
 */
IdmUserMetaNamespace.prototype['JsonDefinition'] = undefined;

/**
 * @member {String} Label
 */
IdmUserMetaNamespace.prototype['Label'] = undefined;

/**
 * @member {String} Namespace
 */
IdmUserMetaNamespace.prototype['Namespace'] = undefined;

/**
 * @member {Number} Order
 */
IdmUserMetaNamespace.prototype['Order'] = undefined;

/**
 * @member {Array.<module:model/ServiceResourcePolicy>} Policies
 */
IdmUserMetaNamespace.prototype['Policies'] = undefined;

/**
 * @member {Boolean} PoliciesContextEditable
 */
IdmUserMetaNamespace.prototype['PoliciesContextEditable'] = undefined;






export default IdmUserMetaNamespace;

