/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmWorkspaceScope from './IdmWorkspaceScope';

/**
 * The IdmWorkspaceSingleQuery model module.
 * @module model/IdmWorkspaceSingleQuery
 * @version 4.0
 */
class IdmWorkspaceSingleQuery {
    /**
     * Constructs a new <code>IdmWorkspaceSingleQuery</code>.
     * @alias module:model/IdmWorkspaceSingleQuery
     */
    constructor() { 
        
        IdmWorkspaceSingleQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmWorkspaceSingleQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmWorkspaceSingleQuery} obj Optional instance to populate.
     * @return {module:model/IdmWorkspaceSingleQuery} The populated <code>IdmWorkspaceSingleQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmWorkspaceSingleQuery();

            if (data.hasOwnProperty('AttributeName')) {
                obj['AttributeName'] = ApiClient.convertToType(data['AttributeName'], 'String');
            }
            if (data.hasOwnProperty('AttributeValue')) {
                obj['AttributeValue'] = ApiClient.convertToType(data['AttributeValue'], 'String');
            }
            if (data.hasOwnProperty('HasAttribute')) {
                obj['HasAttribute'] = ApiClient.convertToType(data['HasAttribute'], 'String');
            }
            if (data.hasOwnProperty('LastUpdated')) {
                obj['LastUpdated'] = ApiClient.convertToType(data['LastUpdated'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('not')) {
                obj['not'] = ApiClient.convertToType(data['not'], 'Boolean');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = IdmWorkspaceScope.constructFromObject(data['scope']);
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} AttributeName
 */
IdmWorkspaceSingleQuery.prototype['AttributeName'] = undefined;

/**
 * @member {String} AttributeValue
 */
IdmWorkspaceSingleQuery.prototype['AttributeValue'] = undefined;

/**
 * @member {String} HasAttribute
 */
IdmWorkspaceSingleQuery.prototype['HasAttribute'] = undefined;

/**
 * @member {String} LastUpdated
 */
IdmWorkspaceSingleQuery.prototype['LastUpdated'] = undefined;

/**
 * @member {String} description
 */
IdmWorkspaceSingleQuery.prototype['description'] = undefined;

/**
 * @member {String} label
 */
IdmWorkspaceSingleQuery.prototype['label'] = undefined;

/**
 * @member {Boolean} not
 */
IdmWorkspaceSingleQuery.prototype['not'] = undefined;

/**
 * @member {module:model/IdmWorkspaceScope} scope
 */
IdmWorkspaceSingleQuery.prototype['scope'] = undefined;

/**
 * @member {String} slug
 */
IdmWorkspaceSingleQuery.prototype['slug'] = undefined;

/**
 * @member {String} uuid
 */
IdmWorkspaceSingleQuery.prototype['uuid'] = undefined;






export default IdmWorkspaceSingleQuery;

