/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstallInstallConfig from './InstallInstallConfig';

/**
 * The InstallPerformCheckRequest model module.
 * @module model/InstallPerformCheckRequest
 * @version 4.0
 */
class InstallPerformCheckRequest {
    /**
     * Constructs a new <code>InstallPerformCheckRequest</code>.
     * @alias module:model/InstallPerformCheckRequest
     */
    constructor() { 
        
        InstallPerformCheckRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstallPerformCheckRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstallPerformCheckRequest} obj Optional instance to populate.
     * @return {module:model/InstallPerformCheckRequest} The populated <code>InstallPerformCheckRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstallPerformCheckRequest();

            if (data.hasOwnProperty('Config')) {
                obj['Config'] = InstallInstallConfig.constructFromObject(data['Config']);
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstallPerformCheckRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstallPerformCheckRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Config`
        if (data['Config']) { // data not null
          InstallInstallConfig.validateJSON(data['Config']);
        }
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }

        return true;
    }


}



/**
 * @member {module:model/InstallInstallConfig} Config
 */
InstallPerformCheckRequest.prototype['Config'] = undefined;

/**
 * @member {String} Name
 */
InstallPerformCheckRequest.prototype['Name'] = undefined;






export default InstallPerformCheckRequest;

