/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstallCorsOptions model module.
 * @module model/InstallCorsOptions
 * @version 4.0
 */
class InstallCorsOptions {
    /**
     * Constructs a new <code>InstallCorsOptions</code>.
     * @alias module:model/InstallCorsOptions
     */
    constructor() { 
        
        InstallCorsOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstallCorsOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstallCorsOptions} obj Optional instance to populate.
     * @return {module:model/InstallCorsOptions} The populated <code>InstallCorsOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstallCorsOptions();

            if (data.hasOwnProperty('AllowCredentials')) {
                obj['AllowCredentials'] = ApiClient.convertToType(data['AllowCredentials'], 'Boolean');
            }
            if (data.hasOwnProperty('AllowPrivateNetwork')) {
                obj['AllowPrivateNetwork'] = ApiClient.convertToType(data['AllowPrivateNetwork'], 'Boolean');
            }
            if (data.hasOwnProperty('AllowedHeaders')) {
                obj['AllowedHeaders'] = ApiClient.convertToType(data['AllowedHeaders'], ['String']);
            }
            if (data.hasOwnProperty('AllowedMethods')) {
                obj['AllowedMethods'] = ApiClient.convertToType(data['AllowedMethods'], ['String']);
            }
            if (data.hasOwnProperty('AllowedOrigins')) {
                obj['AllowedOrigins'] = ApiClient.convertToType(data['AllowedOrigins'], ['String']);
            }
            if (data.hasOwnProperty('ExposedHeaders')) {
                obj['ExposedHeaders'] = ApiClient.convertToType(data['ExposedHeaders'], ['String']);
            }
            if (data.hasOwnProperty('MaxAge')) {
                obj['MaxAge'] = ApiClient.convertToType(data['MaxAge'], 'Number');
            }
            if (data.hasOwnProperty('OptionsPassthrough')) {
                obj['OptionsPassthrough'] = ApiClient.convertToType(data['OptionsPassthrough'], 'Boolean');
            }
            if (data.hasOwnProperty('OptionsSuccessStatus')) {
                obj['OptionsSuccessStatus'] = ApiClient.convertToType(data['OptionsSuccessStatus'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstallCorsOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstallCorsOptions</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['AllowedHeaders'])) {
            throw new Error("Expected the field `AllowedHeaders` to be an array in the JSON data but got " + data['AllowedHeaders']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['AllowedMethods'])) {
            throw new Error("Expected the field `AllowedMethods` to be an array in the JSON data but got " + data['AllowedMethods']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['AllowedOrigins'])) {
            throw new Error("Expected the field `AllowedOrigins` to be an array in the JSON data but got " + data['AllowedOrigins']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ExposedHeaders'])) {
            throw new Error("Expected the field `ExposedHeaders` to be an array in the JSON data but got " + data['ExposedHeaders']);
        }

        return true;
    }


}



/**
 * @member {Boolean} AllowCredentials
 */
InstallCorsOptions.prototype['AllowCredentials'] = undefined;

/**
 * @member {Boolean} AllowPrivateNetwork
 */
InstallCorsOptions.prototype['AllowPrivateNetwork'] = undefined;

/**
 * @member {Array.<String>} AllowedHeaders
 */
InstallCorsOptions.prototype['AllowedHeaders'] = undefined;

/**
 * @member {Array.<String>} AllowedMethods
 */
InstallCorsOptions.prototype['AllowedMethods'] = undefined;

/**
 * @member {Array.<String>} AllowedOrigins
 */
InstallCorsOptions.prototype['AllowedOrigins'] = undefined;

/**
 * @member {Array.<String>} ExposedHeaders
 */
InstallCorsOptions.prototype['ExposedHeaders'] = undefined;

/**
 * @member {Number} MaxAge
 */
InstallCorsOptions.prototype['MaxAge'] = undefined;

/**
 * @member {Boolean} OptionsPassthrough
 */
InstallCorsOptions.prototype['OptionsPassthrough'] = undefined;

/**
 * @member {Number} OptionsSuccessStatus
 */
InstallCorsOptions.prototype['OptionsSuccessStatus'] = undefined;






export default InstallCorsOptions;

