/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobsActionOutput model module.
 * @module model/JobsActionOutput
 * @version 4.0
 */
class JobsActionOutput {
    /**
     * Constructs a new <code>JobsActionOutput</code>.
     * @alias module:model/JobsActionOutput
     */
    constructor() { 
        
        JobsActionOutput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobsActionOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobsActionOutput} obj Optional instance to populate.
     * @return {module:model/JobsActionOutput} The populated <code>JobsActionOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobsActionOutput();

            if (data.hasOwnProperty('ErrorString')) {
                obj['ErrorString'] = ApiClient.convertToType(data['ErrorString'], 'String');
            }
            if (data.hasOwnProperty('Ignored')) {
                obj['Ignored'] = ApiClient.convertToType(data['Ignored'], 'Boolean');
            }
            if (data.hasOwnProperty('JsonBody')) {
                obj['JsonBody'] = ApiClient.convertToType(data['JsonBody'], 'Blob');
            }
            if (data.hasOwnProperty('RawBody')) {
                obj['RawBody'] = ApiClient.convertToType(data['RawBody'], 'Blob');
            }
            if (data.hasOwnProperty('StringBody')) {
                obj['StringBody'] = ApiClient.convertToType(data['StringBody'], 'String');
            }
            if (data.hasOwnProperty('Success')) {
                obj['Success'] = ApiClient.convertToType(data['Success'], 'Boolean');
            }
            if (data.hasOwnProperty('Time')) {
                obj['Time'] = ApiClient.convertToType(data['Time'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} ErrorString
 */
JobsActionOutput.prototype['ErrorString'] = undefined;

/**
 * @member {Boolean} Ignored
 */
JobsActionOutput.prototype['Ignored'] = undefined;

/**
 * @member {Blob} JsonBody
 */
JobsActionOutput.prototype['JsonBody'] = undefined;

/**
 * @member {Blob} RawBody
 */
JobsActionOutput.prototype['RawBody'] = undefined;

/**
 * @member {String} StringBody
 */
JobsActionOutput.prototype['StringBody'] = undefined;

/**
 * @member {Boolean} Success
 */
JobsActionOutput.prototype['Success'] = undefined;

/**
 * @member {Number} Time
 */
JobsActionOutput.prototype['Time'] = undefined;






export default JobsActionOutput;

