/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class JobsContextMetaFilterType.
* @enum {}
* @readonly
*/
export default class JobsContextMetaFilterType {
    
        /**
         * value: "RequestMeta"
         * @const
         */
        "RequestMeta" = "RequestMeta";

    
        /**
         * value: "ContextUser"
         * @const
         */
        "ContextUser" = "ContextUser";

    

    /**
    * Returns a <code>JobsContextMetaFilterType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/JobsContextMetaFilterType} The enum <code>JobsContextMetaFilterType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

