/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobsAction from './JobsAction';
import JobsContextMetaFilter from './JobsContextMetaFilter';
import JobsDataSourceSelector from './JobsDataSourceSelector';
import JobsIdmSelector from './JobsIdmSelector';
import JobsJobHook from './JobsJobHook';
import JobsJobParameter from './JobsJobParameter';
import JobsNodesSelector from './JobsNodesSelector';
import JobsSchedule from './JobsSchedule';
import JobsTask from './JobsTask';
import JobsUsersSelector from './JobsUsersSelector';
import ProtobufAny from './ProtobufAny';

/**
 * The JobsJob model module.
 * @module model/JobsJob
 * @version 4.0
 */
class JobsJob {
    /**
     * Constructs a new <code>JobsJob</code>.
     * @alias module:model/JobsJob
     */
    constructor() { 
        
        JobsJob.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobsJob</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobsJob} obj Optional instance to populate.
     * @return {module:model/JobsJob} The populated <code>JobsJob</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobsJob();

            if (data.hasOwnProperty('Actions')) {
                obj['Actions'] = ApiClient.convertToType(data['Actions'], [JobsAction]);
            }
            if (data.hasOwnProperty('AutoClean')) {
                obj['AutoClean'] = ApiClient.convertToType(data['AutoClean'], 'Boolean');
            }
            if (data.hasOwnProperty('AutoRestart')) {
                obj['AutoRestart'] = ApiClient.convertToType(data['AutoRestart'], 'Boolean');
            }
            if (data.hasOwnProperty('AutoStart')) {
                obj['AutoStart'] = ApiClient.convertToType(data['AutoStart'], 'Boolean');
            }
            if (data.hasOwnProperty('ContextMetaFilter')) {
                obj['ContextMetaFilter'] = JobsContextMetaFilter.constructFromObject(data['ContextMetaFilter']);
            }
            if (data.hasOwnProperty('CreatedAt')) {
                obj['CreatedAt'] = ApiClient.convertToType(data['CreatedAt'], 'Number');
            }
            if (data.hasOwnProperty('Custom')) {
                obj['Custom'] = ApiClient.convertToType(data['Custom'], 'Boolean');
            }
            if (data.hasOwnProperty('DataSourceFilter')) {
                obj['DataSourceFilter'] = JobsDataSourceSelector.constructFromObject(data['DataSourceFilter']);
            }
            if (data.hasOwnProperty('EventNames')) {
                obj['EventNames'] = ApiClient.convertToType(data['EventNames'], ['String']);
            }
            if (data.hasOwnProperty('Hooks')) {
                obj['Hooks'] = ApiClient.convertToType(data['Hooks'], [JobsJobHook]);
            }
            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
            }
            if (data.hasOwnProperty('IdmFilter')) {
                obj['IdmFilter'] = JobsIdmSelector.constructFromObject(data['IdmFilter']);
            }
            if (data.hasOwnProperty('Inactive')) {
                obj['Inactive'] = ApiClient.convertToType(data['Inactive'], 'Boolean');
            }
            if (data.hasOwnProperty('Label')) {
                obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
            }
            if (data.hasOwnProperty('Languages')) {
                obj['Languages'] = ApiClient.convertToType(data['Languages'], ['String']);
            }
            if (data.hasOwnProperty('MaxConcurrency')) {
                obj['MaxConcurrency'] = ApiClient.convertToType(data['MaxConcurrency'], 'Number');
            }
            if (data.hasOwnProperty('MergeAction')) {
                obj['MergeAction'] = JobsAction.constructFromObject(data['MergeAction']);
            }
            if (data.hasOwnProperty('Metadata')) {
                obj['Metadata'] = ApiClient.convertToType(data['Metadata'], {'String': 'String'});
            }
            if (data.hasOwnProperty('ModifiedAt')) {
                obj['ModifiedAt'] = ApiClient.convertToType(data['ModifiedAt'], 'Number');
            }
            if (data.hasOwnProperty('NodeEventFilter')) {
                obj['NodeEventFilter'] = JobsNodesSelector.constructFromObject(data['NodeEventFilter']);
            }
            if (data.hasOwnProperty('Owner')) {
                obj['Owner'] = ApiClient.convertToType(data['Owner'], 'String');
            }
            if (data.hasOwnProperty('Parameters')) {
                obj['Parameters'] = ApiClient.convertToType(data['Parameters'], [JobsJobParameter]);
            }
            if (data.hasOwnProperty('ResourcesDependencies')) {
                obj['ResourcesDependencies'] = ApiClient.convertToType(data['ResourcesDependencies'], [ProtobufAny]);
            }
            if (data.hasOwnProperty('Schedule')) {
                obj['Schedule'] = JobsSchedule.constructFromObject(data['Schedule']);
            }
            if (data.hasOwnProperty('Tasks')) {
                obj['Tasks'] = ApiClient.convertToType(data['Tasks'], [JobsTask]);
            }
            if (data.hasOwnProperty('TasksSilentUpdate')) {
                obj['TasksSilentUpdate'] = ApiClient.convertToType(data['TasksSilentUpdate'], 'Boolean');
            }
            if (data.hasOwnProperty('Timeout')) {
                obj['Timeout'] = ApiClient.convertToType(data['Timeout'], 'String');
            }
            if (data.hasOwnProperty('UserEventFilter')) {
                obj['UserEventFilter'] = JobsUsersSelector.constructFromObject(data['UserEventFilter']);
            }
            if (data.hasOwnProperty('VersionMeta')) {
                obj['VersionMeta'] = ApiClient.convertToType(data['VersionMeta'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobsJob</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobsJob</code>.
     */
    static validateJSON(data) {
        if (data['Actions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Actions'])) {
                throw new Error("Expected the field `Actions` to be an array in the JSON data but got " + data['Actions']);
            }
            // validate the optional field `Actions` (array)
            for (const item of data['Actions']) {
                JobsAction.validateJSON(item);
            };
        }
        // validate the optional field `ContextMetaFilter`
        if (data['ContextMetaFilter']) { // data not null
          JobsContextMetaFilter.validateJSON(data['ContextMetaFilter']);
        }
        // validate the optional field `DataSourceFilter`
        if (data['DataSourceFilter']) { // data not null
          JobsDataSourceSelector.validateJSON(data['DataSourceFilter']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['EventNames'])) {
            throw new Error("Expected the field `EventNames` to be an array in the JSON data but got " + data['EventNames']);
        }
        if (data['Hooks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Hooks'])) {
                throw new Error("Expected the field `Hooks` to be an array in the JSON data but got " + data['Hooks']);
            }
            // validate the optional field `Hooks` (array)
            for (const item of data['Hooks']) {
                JobsJobHook.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['ID'] && !(typeof data['ID'] === 'string' || data['ID'] instanceof String)) {
            throw new Error("Expected the field `ID` to be a primitive type in the JSON string but got " + data['ID']);
        }
        // validate the optional field `IdmFilter`
        if (data['IdmFilter']) { // data not null
          JobsIdmSelector.validateJSON(data['IdmFilter']);
        }
        // ensure the json data is a string
        if (data['Label'] && !(typeof data['Label'] === 'string' || data['Label'] instanceof String)) {
            throw new Error("Expected the field `Label` to be a primitive type in the JSON string but got " + data['Label']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['Languages'])) {
            throw new Error("Expected the field `Languages` to be an array in the JSON data but got " + data['Languages']);
        }
        // validate the optional field `MergeAction`
        if (data['MergeAction']) { // data not null
          JobsAction.validateJSON(data['MergeAction']);
        }
        // validate the optional field `NodeEventFilter`
        if (data['NodeEventFilter']) { // data not null
          JobsNodesSelector.validateJSON(data['NodeEventFilter']);
        }
        // ensure the json data is a string
        if (data['Owner'] && !(typeof data['Owner'] === 'string' || data['Owner'] instanceof String)) {
            throw new Error("Expected the field `Owner` to be a primitive type in the JSON string but got " + data['Owner']);
        }
        if (data['Parameters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Parameters'])) {
                throw new Error("Expected the field `Parameters` to be an array in the JSON data but got " + data['Parameters']);
            }
            // validate the optional field `Parameters` (array)
            for (const item of data['Parameters']) {
                JobsJobParameter.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ResourcesDependencies'])) {
            throw new Error("Expected the field `ResourcesDependencies` to be an array in the JSON data but got " + data['ResourcesDependencies']);
        }
        // validate the optional field `Schedule`
        if (data['Schedule']) { // data not null
          JobsSchedule.validateJSON(data['Schedule']);
        }
        if (data['Tasks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Tasks'])) {
                throw new Error("Expected the field `Tasks` to be an array in the JSON data but got " + data['Tasks']);
            }
            // validate the optional field `Tasks` (array)
            for (const item of data['Tasks']) {
                JobsTask.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['Timeout'] && !(typeof data['Timeout'] === 'string' || data['Timeout'] instanceof String)) {
            throw new Error("Expected the field `Timeout` to be a primitive type in the JSON string but got " + data['Timeout']);
        }
        // validate the optional field `UserEventFilter`
        if (data['UserEventFilter']) { // data not null
          JobsUsersSelector.validateJSON(data['UserEventFilter']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/JobsAction>} Actions
 */
JobsJob.prototype['Actions'] = undefined;

/**
 * @member {Boolean} AutoClean
 */
JobsJob.prototype['AutoClean'] = undefined;

/**
 * @member {Boolean} AutoRestart
 */
JobsJob.prototype['AutoRestart'] = undefined;

/**
 * @member {Boolean} AutoStart
 */
JobsJob.prototype['AutoStart'] = undefined;

/**
 * @member {module:model/JobsContextMetaFilter} ContextMetaFilter
 */
JobsJob.prototype['ContextMetaFilter'] = undefined;

/**
 * @member {Number} CreatedAt
 */
JobsJob.prototype['CreatedAt'] = undefined;

/**
 * @member {Boolean} Custom
 */
JobsJob.prototype['Custom'] = undefined;

/**
 * @member {module:model/JobsDataSourceSelector} DataSourceFilter
 */
JobsJob.prototype['DataSourceFilter'] = undefined;

/**
 * @member {Array.<String>} EventNames
 */
JobsJob.prototype['EventNames'] = undefined;

/**
 * @member {Array.<module:model/JobsJobHook>} Hooks
 */
JobsJob.prototype['Hooks'] = undefined;

/**
 * @member {String} ID
 */
JobsJob.prototype['ID'] = undefined;

/**
 * @member {module:model/JobsIdmSelector} IdmFilter
 */
JobsJob.prototype['IdmFilter'] = undefined;

/**
 * @member {Boolean} Inactive
 */
JobsJob.prototype['Inactive'] = undefined;

/**
 * @member {String} Label
 */
JobsJob.prototype['Label'] = undefined;

/**
 * @member {Array.<String>} Languages
 */
JobsJob.prototype['Languages'] = undefined;

/**
 * @member {Number} MaxConcurrency
 */
JobsJob.prototype['MaxConcurrency'] = undefined;

/**
 * @member {module:model/JobsAction} MergeAction
 */
JobsJob.prototype['MergeAction'] = undefined;

/**
 * Additional user-defined metadata, can be used for icon, documentation, pre-requisites, etc.
 * @member {Object.<String, String>} Metadata
 */
JobsJob.prototype['Metadata'] = undefined;

/**
 * @member {Number} ModifiedAt
 */
JobsJob.prototype['ModifiedAt'] = undefined;

/**
 * @member {module:model/JobsNodesSelector} NodeEventFilter
 */
JobsJob.prototype['NodeEventFilter'] = undefined;

/**
 * @member {String} Owner
 */
JobsJob.prototype['Owner'] = undefined;

/**
 * @member {Array.<module:model/JobsJobParameter>} Parameters
 */
JobsJob.prototype['Parameters'] = undefined;

/**
 * @member {Array.<module:model/ProtobufAny>} ResourcesDependencies
 */
JobsJob.prototype['ResourcesDependencies'] = undefined;

/**
 * @member {module:model/JobsSchedule} Schedule
 */
JobsJob.prototype['Schedule'] = undefined;

/**
 * @member {Array.<module:model/JobsTask>} Tasks
 */
JobsJob.prototype['Tasks'] = undefined;

/**
 * @member {Boolean} TasksSilentUpdate
 */
JobsJob.prototype['TasksSilentUpdate'] = undefined;

/**
 * @member {String} Timeout
 */
JobsJob.prototype['Timeout'] = undefined;

/**
 * @member {module:model/JobsUsersSelector} UserEventFilter
 */
JobsJob.prototype['UserEventFilter'] = undefined;

/**
 * @member {Object.<String, String>} VersionMeta
 */
JobsJob.prototype['VersionMeta'] = undefined;






export default JobsJob;

