/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobsActionLog from './JobsActionLog';
import JobsTaskStatus from './JobsTaskStatus';

/**
 * The JobsTask model module.
 * @module model/JobsTask
 * @version 4.0
 */
class JobsTask {
    /**
     * Constructs a new <code>JobsTask</code>.
     * @alias module:model/JobsTask
     */
    constructor() { 
        
        JobsTask.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobsTask</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobsTask} obj Optional instance to populate.
     * @return {module:model/JobsTask} The populated <code>JobsTask</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobsTask();

            if (data.hasOwnProperty('ActionsLogs')) {
                obj['ActionsLogs'] = ApiClient.convertToType(data['ActionsLogs'], [JobsActionLog]);
            }
            if (data.hasOwnProperty('CanPause')) {
                obj['CanPause'] = ApiClient.convertToType(data['CanPause'], 'Boolean');
            }
            if (data.hasOwnProperty('CanStop')) {
                obj['CanStop'] = ApiClient.convertToType(data['CanStop'], 'Boolean');
            }
            if (data.hasOwnProperty('EndTime')) {
                obj['EndTime'] = ApiClient.convertToType(data['EndTime'], 'Number');
            }
            if (data.hasOwnProperty('HasProgress')) {
                obj['HasProgress'] = ApiClient.convertToType(data['HasProgress'], 'Boolean');
            }
            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
            }
            if (data.hasOwnProperty('JobID')) {
                obj['JobID'] = ApiClient.convertToType(data['JobID'], 'String');
            }
            if (data.hasOwnProperty('Progress')) {
                obj['Progress'] = ApiClient.convertToType(data['Progress'], 'Number');
            }
            if (data.hasOwnProperty('StartTime')) {
                obj['StartTime'] = ApiClient.convertToType(data['StartTime'], 'Number');
            }
            if (data.hasOwnProperty('Status')) {
                obj['Status'] = JobsTaskStatus.constructFromObject(data['Status']);
            }
            if (data.hasOwnProperty('StatusMessage')) {
                obj['StatusMessage'] = ApiClient.convertToType(data['StatusMessage'], 'String');
            }
            if (data.hasOwnProperty('TriggerOwner')) {
                obj['TriggerOwner'] = ApiClient.convertToType(data['TriggerOwner'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/JobsActionLog>} ActionsLogs
 */
JobsTask.prototype['ActionsLogs'] = undefined;

/**
 * @member {Boolean} CanPause
 */
JobsTask.prototype['CanPause'] = undefined;

/**
 * @member {Boolean} CanStop
 */
JobsTask.prototype['CanStop'] = undefined;

/**
 * @member {Number} EndTime
 */
JobsTask.prototype['EndTime'] = undefined;

/**
 * @member {Boolean} HasProgress
 */
JobsTask.prototype['HasProgress'] = undefined;

/**
 * @member {String} ID
 */
JobsTask.prototype['ID'] = undefined;

/**
 * @member {String} JobID
 */
JobsTask.prototype['JobID'] = undefined;

/**
 * @member {Number} Progress
 */
JobsTask.prototype['Progress'] = undefined;

/**
 * @member {Number} StartTime
 */
JobsTask.prototype['StartTime'] = undefined;

/**
 * @member {module:model/JobsTaskStatus} Status
 */
JobsTask.prototype['Status'] = undefined;

/**
 * @member {String} StatusMessage
 */
JobsTask.prototype['StatusMessage'] = undefined;

/**
 * @member {String} TriggerOwner
 */
JobsTask.prototype['TriggerOwner'] = undefined;






export default JobsTask;

