/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobsJobParameter model module.
 * @module model/JobsJobParameter
 * @version 4.0
 */
class JobsJobParameter {
    /**
     * Constructs a new <code>JobsJobParameter</code>.
     * @alias module:model/JobsJobParameter
     */
    constructor() { 
        
        JobsJobParameter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobsJobParameter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobsJobParameter} obj Optional instance to populate.
     * @return {module:model/JobsJobParameter} The populated <code>JobsJobParameter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobsJobParameter();

            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('JsonChoices')) {
                obj['JsonChoices'] = ApiClient.convertToType(data['JsonChoices'], 'String');
            }
            if (data.hasOwnProperty('Mandatory')) {
                obj['Mandatory'] = ApiClient.convertToType(data['Mandatory'], 'Boolean');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('Type')) {
                obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
            }
            if (data.hasOwnProperty('Value')) {
                obj['Value'] = ApiClient.convertToType(data['Value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobsJobParameter</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobsJobParameter</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Description'] && !(typeof data['Description'] === 'string' || data['Description'] instanceof String)) {
            throw new Error("Expected the field `Description` to be a primitive type in the JSON string but got " + data['Description']);
        }
        // ensure the json data is a string
        if (data['JsonChoices'] && !(typeof data['JsonChoices'] === 'string' || data['JsonChoices'] instanceof String)) {
            throw new Error("Expected the field `JsonChoices` to be a primitive type in the JSON string but got " + data['JsonChoices']);
        }
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is a string
        if (data['Type'] && !(typeof data['Type'] === 'string' || data['Type'] instanceof String)) {
            throw new Error("Expected the field `Type` to be a primitive type in the JSON string but got " + data['Type']);
        }
        // ensure the json data is a string
        if (data['Value'] && !(typeof data['Value'] === 'string' || data['Value'] instanceof String)) {
            throw new Error("Expected the field `Value` to be a primitive type in the JSON string but got " + data['Value']);
        }

        return true;
    }


}



/**
 * @member {String} Description
 */
JobsJobParameter.prototype['Description'] = undefined;

/**
 * @member {String} JsonChoices
 */
JobsJobParameter.prototype['JsonChoices'] = undefined;

/**
 * @member {Boolean} Mandatory
 */
JobsJobParameter.prototype['Mandatory'] = undefined;

/**
 * @member {String} Name
 */
JobsJobParameter.prototype['Name'] = undefined;

/**
 * @member {String} Type
 */
JobsJobParameter.prototype['Type'] = undefined;

/**
 * @member {String} Value
 */
JobsJobParameter.prototype['Value'] = undefined;






export default JobsJobParameter;

