/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectEncryptionMode from './ObjectEncryptionMode';
import ObjectStorageType from './ObjectStorageType';

/**
 * The ObjectDataSource model module.
 * @module model/ObjectDataSource
 * @version 4.0
 */
class ObjectDataSource {
    /**
     * Constructs a new <code>ObjectDataSource</code>.
     * @alias module:model/ObjectDataSource
     */
    constructor() { 
        
        ObjectDataSource.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ObjectDataSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjectDataSource} obj Optional instance to populate.
     * @return {module:model/ObjectDataSource} The populated <code>ObjectDataSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectDataSource();

            if (data.hasOwnProperty('ApiKey')) {
                obj['ApiKey'] = ApiClient.convertToType(data['ApiKey'], 'String');
            }
            if (data.hasOwnProperty('ApiSecret')) {
                obj['ApiSecret'] = ApiClient.convertToType(data['ApiSecret'], 'String');
            }
            if (data.hasOwnProperty('CreationDate')) {
                obj['CreationDate'] = ApiClient.convertToType(data['CreationDate'], 'Number');
            }
            if (data.hasOwnProperty('Disabled')) {
                obj['Disabled'] = ApiClient.convertToType(data['Disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('EncryptionKey')) {
                obj['EncryptionKey'] = ApiClient.convertToType(data['EncryptionKey'], 'String');
            }
            if (data.hasOwnProperty('EncryptionMode')) {
                obj['EncryptionMode'] = ObjectEncryptionMode.constructFromObject(data['EncryptionMode']);
            }
            if (data.hasOwnProperty('FlatStorage')) {
                obj['FlatStorage'] = ApiClient.convertToType(data['FlatStorage'], 'Boolean');
            }
            if (data.hasOwnProperty('LastSynchronizationDate')) {
                obj['LastSynchronizationDate'] = ApiClient.convertToType(data['LastSynchronizationDate'], 'Number');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('ObjectsBaseFolder')) {
                obj['ObjectsBaseFolder'] = ApiClient.convertToType(data['ObjectsBaseFolder'], 'String');
            }
            if (data.hasOwnProperty('ObjectsBucket')) {
                obj['ObjectsBucket'] = ApiClient.convertToType(data['ObjectsBucket'], 'String');
            }
            if (data.hasOwnProperty('ObjectsHost')) {
                obj['ObjectsHost'] = ApiClient.convertToType(data['ObjectsHost'], 'String');
            }
            if (data.hasOwnProperty('ObjectsPort')) {
                obj['ObjectsPort'] = ApiClient.convertToType(data['ObjectsPort'], 'Number');
            }
            if (data.hasOwnProperty('ObjectsSecure')) {
                obj['ObjectsSecure'] = ApiClient.convertToType(data['ObjectsSecure'], 'Boolean');
            }
            if (data.hasOwnProperty('ObjectsServiceName')) {
                obj['ObjectsServiceName'] = ApiClient.convertToType(data['ObjectsServiceName'], 'String');
            }
            if (data.hasOwnProperty('PeerAddress')) {
                obj['PeerAddress'] = ApiClient.convertToType(data['PeerAddress'], 'String');
            }
            if (data.hasOwnProperty('SkipSyncOnRestart')) {
                obj['SkipSyncOnRestart'] = ApiClient.convertToType(data['SkipSyncOnRestart'], 'Boolean');
            }
            if (data.hasOwnProperty('StorageConfiguration')) {
                obj['StorageConfiguration'] = ApiClient.convertToType(data['StorageConfiguration'], {'String': 'String'});
            }
            if (data.hasOwnProperty('StorageType')) {
                obj['StorageType'] = ObjectStorageType.constructFromObject(data['StorageType']);
            }
            if (data.hasOwnProperty('VersioningPolicyName')) {
                obj['VersioningPolicyName'] = ApiClient.convertToType(data['VersioningPolicyName'], 'String');
            }
            if (data.hasOwnProperty('Watch')) {
                obj['Watch'] = ApiClient.convertToType(data['Watch'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObjectDataSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObjectDataSource</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ApiKey'] && !(typeof data['ApiKey'] === 'string' || data['ApiKey'] instanceof String)) {
            throw new Error("Expected the field `ApiKey` to be a primitive type in the JSON string but got " + data['ApiKey']);
        }
        // ensure the json data is a string
        if (data['ApiSecret'] && !(typeof data['ApiSecret'] === 'string' || data['ApiSecret'] instanceof String)) {
            throw new Error("Expected the field `ApiSecret` to be a primitive type in the JSON string but got " + data['ApiSecret']);
        }
        // ensure the json data is a string
        if (data['EncryptionKey'] && !(typeof data['EncryptionKey'] === 'string' || data['EncryptionKey'] instanceof String)) {
            throw new Error("Expected the field `EncryptionKey` to be a primitive type in the JSON string but got " + data['EncryptionKey']);
        }
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is a string
        if (data['ObjectsBaseFolder'] && !(typeof data['ObjectsBaseFolder'] === 'string' || data['ObjectsBaseFolder'] instanceof String)) {
            throw new Error("Expected the field `ObjectsBaseFolder` to be a primitive type in the JSON string but got " + data['ObjectsBaseFolder']);
        }
        // ensure the json data is a string
        if (data['ObjectsBucket'] && !(typeof data['ObjectsBucket'] === 'string' || data['ObjectsBucket'] instanceof String)) {
            throw new Error("Expected the field `ObjectsBucket` to be a primitive type in the JSON string but got " + data['ObjectsBucket']);
        }
        // ensure the json data is a string
        if (data['ObjectsHost'] && !(typeof data['ObjectsHost'] === 'string' || data['ObjectsHost'] instanceof String)) {
            throw new Error("Expected the field `ObjectsHost` to be a primitive type in the JSON string but got " + data['ObjectsHost']);
        }
        // ensure the json data is a string
        if (data['ObjectsServiceName'] && !(typeof data['ObjectsServiceName'] === 'string' || data['ObjectsServiceName'] instanceof String)) {
            throw new Error("Expected the field `ObjectsServiceName` to be a primitive type in the JSON string but got " + data['ObjectsServiceName']);
        }
        // ensure the json data is a string
        if (data['PeerAddress'] && !(typeof data['PeerAddress'] === 'string' || data['PeerAddress'] instanceof String)) {
            throw new Error("Expected the field `PeerAddress` to be a primitive type in the JSON string but got " + data['PeerAddress']);
        }
        // ensure the json data is a string
        if (data['VersioningPolicyName'] && !(typeof data['VersioningPolicyName'] === 'string' || data['VersioningPolicyName'] instanceof String)) {
            throw new Error("Expected the field `VersioningPolicyName` to be a primitive type in the JSON string but got " + data['VersioningPolicyName']);
        }

        return true;
    }


}



/**
 * @member {String} ApiKey
 */
ObjectDataSource.prototype['ApiKey'] = undefined;

/**
 * @member {String} ApiSecret
 */
ObjectDataSource.prototype['ApiSecret'] = undefined;

/**
 * @member {Number} CreationDate
 */
ObjectDataSource.prototype['CreationDate'] = undefined;

/**
 * @member {Boolean} Disabled
 */
ObjectDataSource.prototype['Disabled'] = undefined;

/**
 * @member {String} EncryptionKey
 */
ObjectDataSource.prototype['EncryptionKey'] = undefined;

/**
 * @member {module:model/ObjectEncryptionMode} EncryptionMode
 */
ObjectDataSource.prototype['EncryptionMode'] = undefined;

/**
 * @member {Boolean} FlatStorage
 */
ObjectDataSource.prototype['FlatStorage'] = undefined;

/**
 * @member {Number} LastSynchronizationDate
 */
ObjectDataSource.prototype['LastSynchronizationDate'] = undefined;

/**
 * @member {String} Name
 */
ObjectDataSource.prototype['Name'] = undefined;

/**
 * @member {String} ObjectsBaseFolder
 */
ObjectDataSource.prototype['ObjectsBaseFolder'] = undefined;

/**
 * @member {String} ObjectsBucket
 */
ObjectDataSource.prototype['ObjectsBucket'] = undefined;

/**
 * @member {String} ObjectsHost
 */
ObjectDataSource.prototype['ObjectsHost'] = undefined;

/**
 * @member {Number} ObjectsPort
 */
ObjectDataSource.prototype['ObjectsPort'] = undefined;

/**
 * @member {Boolean} ObjectsSecure
 */
ObjectDataSource.prototype['ObjectsSecure'] = undefined;

/**
 * @member {String} ObjectsServiceName
 */
ObjectDataSource.prototype['ObjectsServiceName'] = undefined;

/**
 * @member {String} PeerAddress
 */
ObjectDataSource.prototype['PeerAddress'] = undefined;

/**
 * @member {Boolean} SkipSyncOnRestart
 */
ObjectDataSource.prototype['SkipSyncOnRestart'] = undefined;

/**
 * @member {Object.<String, String>} StorageConfiguration
 */
ObjectDataSource.prototype['StorageConfiguration'] = undefined;

/**
 * @member {module:model/ObjectStorageType} StorageType
 */
ObjectDataSource.prototype['StorageType'] = undefined;

/**
 * @member {String} VersioningPolicyName
 */
ObjectDataSource.prototype['VersioningPolicyName'] = undefined;

/**
 * @member {Boolean} Watch
 */
ObjectDataSource.prototype['Watch'] = undefined;






export default ObjectDataSource;

