/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegistryGeneric model module.
 * @module model/RegistryGeneric
 * @version 4.0
 */
class RegistryGeneric {
    /**
     * Constructs a new <code>RegistryGeneric</code>.
     * @alias module:model/RegistryGeneric
     */
    constructor() { 
        
        RegistryGeneric.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegistryGeneric</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegistryGeneric} obj Optional instance to populate.
     * @return {module:model/RegistryGeneric} The populated <code>RegistryGeneric</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegistryGeneric();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': 'String'});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
RegistryGeneric.prototype['id'] = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
RegistryGeneric.prototype['metadata'] = undefined;

/**
 * @member {String} name
 */
RegistryGeneric.prototype['name'] = undefined;






export default RegistryGeneric;

