/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestResetPasswordResponse model module.
 * @module model/RestResetPasswordResponse
 * @version 4.0
 */
class RestResetPasswordResponse {
    /**
     * Constructs a new <code>RestResetPasswordResponse</code>.
     * @alias module:model/RestResetPasswordResponse
     */
    constructor() { 
        
        RestResetPasswordResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestResetPasswordResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestResetPasswordResponse} obj Optional instance to populate.
     * @return {module:model/RestResetPasswordResponse} The populated <code>RestResetPasswordResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestResetPasswordResponse();

            if (data.hasOwnProperty('Message')) {
                obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
            }
            if (data.hasOwnProperty('Success')) {
                obj['Success'] = ApiClient.convertToType(data['Success'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} Message
 */
RestResetPasswordResponse.prototype['Message'] = undefined;

/**
 * @member {Boolean} Success
 */
RestResetPasswordResponse.prototype['Success'] = undefined;






export default RestResetPasswordResponse;

