/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TreeNode from './TreeNode';

/**
 * The RestHeadNodeResponse model module.
 * @module model/RestHeadNodeResponse
 * @version 4.0
 */
class RestHeadNodeResponse {
    /**
     * Constructs a new <code>RestHeadNodeResponse</code>.
     * @alias module:model/RestHeadNodeResponse
     */
    constructor() { 
        
        RestHeadNodeResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestHeadNodeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestHeadNodeResponse} obj Optional instance to populate.
     * @return {module:model/RestHeadNodeResponse} The populated <code>RestHeadNodeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestHeadNodeResponse();

            if (data.hasOwnProperty('Node')) {
                obj['Node'] = TreeNode.constructFromObject(data['Node']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TreeNode} Node
 */
RestHeadNodeResponse.prototype['Node'] = undefined;






export default RestHeadNodeResponse;

