/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RestPagination from './RestPagination';
import TreeNode from './TreeNode';

/**
 * The RestBulkMetaResponse model module.
 * @module model/RestBulkMetaResponse
 * @version 4.0
 */
class RestBulkMetaResponse {
    /**
     * Constructs a new <code>RestBulkMetaResponse</code>.
     * @alias module:model/RestBulkMetaResponse
     */
    constructor() { 
        
        RestBulkMetaResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestBulkMetaResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestBulkMetaResponse} obj Optional instance to populate.
     * @return {module:model/RestBulkMetaResponse} The populated <code>RestBulkMetaResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestBulkMetaResponse();

            if (data.hasOwnProperty('Nodes')) {
                obj['Nodes'] = ApiClient.convertToType(data['Nodes'], [TreeNode]);
            }
            if (data.hasOwnProperty('Pagination')) {
                obj['Pagination'] = RestPagination.constructFromObject(data['Pagination']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestBulkMetaResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestBulkMetaResponse</code>.
     */
    static validateJSON(data) {
        if (data['Nodes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Nodes'])) {
                throw new Error("Expected the field `Nodes` to be an array in the JSON data but got " + data['Nodes']);
            }
            // validate the optional field `Nodes` (array)
            for (const item of data['Nodes']) {
                TreeNode.validateJSON(item);
            };
        }
        // validate the optional field `Pagination`
        if (data['Pagination']) { // data not null
          RestPagination.validateJSON(data['Pagination']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/TreeNode>} Nodes
 */
RestBulkMetaResponse.prototype['Nodes'] = undefined;

/**
 * @member {module:model/RestPagination} Pagination
 */
RestBulkMetaResponse.prototype['Pagination'] = undefined;






export default RestBulkMetaResponse;

