/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestSettingsAccessRestPolicy model module.
 * @module model/RestSettingsAccessRestPolicy
 * @version 4.0
 */
class RestSettingsAccessRestPolicy {
    /**
     * Constructs a new <code>RestSettingsAccessRestPolicy</code>.
     * @alias module:model/RestSettingsAccessRestPolicy
     */
    constructor() { 
        
        RestSettingsAccessRestPolicy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestSettingsAccessRestPolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestSettingsAccessRestPolicy} obj Optional instance to populate.
     * @return {module:model/RestSettingsAccessRestPolicy} The populated <code>RestSettingsAccessRestPolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestSettingsAccessRestPolicy();

            if (data.hasOwnProperty('Action')) {
                obj['Action'] = ApiClient.convertToType(data['Action'], 'String');
            }
            if (data.hasOwnProperty('Resource')) {
                obj['Resource'] = ApiClient.convertToType(data['Resource'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestSettingsAccessRestPolicy</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestSettingsAccessRestPolicy</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Action'] && !(typeof data['Action'] === 'string' || data['Action'] instanceof String)) {
            throw new Error("Expected the field `Action` to be a primitive type in the JSON string but got " + data['Action']);
        }
        // ensure the json data is a string
        if (data['Resource'] && !(typeof data['Resource'] === 'string' || data['Resource'] instanceof String)) {
            throw new Error("Expected the field `Resource` to be a primitive type in the JSON string but got " + data['Resource']);
        }

        return true;
    }


}



/**
 * @member {String} Action
 */
RestSettingsAccessRestPolicy.prototype['Action'] = undefined;

/**
 * @member {String} Resource
 */
RestSettingsAccessRestPolicy.prototype['Resource'] = undefined;






export default RestSettingsAccessRestPolicy;

