/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestDeleteDataSourceResponse model module.
 * @module model/RestDeleteDataSourceResponse
 * @version 4.0
 */
class RestDeleteDataSourceResponse {
    /**
     * Constructs a new <code>RestDeleteDataSourceResponse</code>.
     * @alias module:model/RestDeleteDataSourceResponse
     */
    constructor() { 
        
        RestDeleteDataSourceResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestDeleteDataSourceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestDeleteDataSourceResponse} obj Optional instance to populate.
     * @return {module:model/RestDeleteDataSourceResponse} The populated <code>RestDeleteDataSourceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestDeleteDataSourceResponse();

            if (data.hasOwnProperty('Success')) {
                obj['Success'] = ApiClient.convertToType(data['Success'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} Success
 */
RestDeleteDataSourceResponse.prototype['Success'] = undefined;






export default RestDeleteDataSourceResponse;

