/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestFrontBootConfResponse model module.
 * @module model/RestFrontBootConfResponse
 * @version 4.0
 */
class RestFrontBootConfResponse {
    /**
     * Constructs a new <code>RestFrontBootConfResponse</code>.
     * @alias module:model/RestFrontBootConfResponse
     */
    constructor() { 
        
        RestFrontBootConfResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestFrontBootConfResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestFrontBootConfResponse} obj Optional instance to populate.
     * @return {module:model/RestFrontBootConfResponse} The populated <code>RestFrontBootConfResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestFrontBootConfResponse();

            if (data.hasOwnProperty('JsonData')) {
                obj['JsonData'] = ApiClient.convertToType(data['JsonData'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, String>} JsonData
 */
RestFrontBootConfResponse.prototype['JsonData'] = undefined;






export default RestFrontBootConfResponse;

