/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RestProcess from './RestProcess';

/**
 * The RestListProcessesResponse model module.
 * @module model/RestListProcessesResponse
 * @version 4.0
 */
class RestListProcessesResponse {
    /**
     * Constructs a new <code>RestListProcessesResponse</code>.
     * @alias module:model/RestListProcessesResponse
     */
    constructor() { 
        
        RestListProcessesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestListProcessesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestListProcessesResponse} obj Optional instance to populate.
     * @return {module:model/RestListProcessesResponse} The populated <code>RestListProcessesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestListProcessesResponse();

            if (data.hasOwnProperty('Processes')) {
                obj['Processes'] = ApiClient.convertToType(data['Processes'], [RestProcess]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/RestProcess>} Processes
 */
RestListProcessesResponse.prototype['Processes'] = undefined;






export default RestListProcessesResponse;

