/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmRole from './IdmRole';
import IdmWorkspace from './IdmWorkspace';

/**
 * The RestRelationResponse model module.
 * @module model/RestRelationResponse
 * @version 4.0
 */
class RestRelationResponse {
    /**
     * Constructs a new <code>RestRelationResponse</code>.
     * @alias module:model/RestRelationResponse
     */
    constructor() { 
        
        RestRelationResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestRelationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestRelationResponse} obj Optional instance to populate.
     * @return {module:model/RestRelationResponse} The populated <code>RestRelationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestRelationResponse();

            if (data.hasOwnProperty('BelongsToTeams')) {
                obj['BelongsToTeams'] = ApiClient.convertToType(data['BelongsToTeams'], [IdmRole]);
            }
            if (data.hasOwnProperty('SharedCells')) {
                obj['SharedCells'] = ApiClient.convertToType(data['SharedCells'], [IdmWorkspace]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/IdmRole>} BelongsToTeams
 */
RestRelationResponse.prototype['BelongsToTeams'] = undefined;

/**
 * @member {Array.<module:model/IdmWorkspace>} SharedCells
 */
RestRelationResponse.prototype['SharedCells'] = undefined;






export default RestRelationResponse;

