/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TreeNode from './TreeNode';

/**
 * The RestNodesCollection model module.
 * @module model/RestNodesCollection
 * @version 4.0
 */
class RestNodesCollection {
    /**
     * Constructs a new <code>RestNodesCollection</code>.
     * @alias module:model/RestNodesCollection
     */
    constructor() { 
        
        RestNodesCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestNodesCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestNodesCollection} obj Optional instance to populate.
     * @return {module:model/RestNodesCollection} The populated <code>RestNodesCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestNodesCollection();

            if (data.hasOwnProperty('Children')) {
                obj['Children'] = ApiClient.convertToType(data['Children'], [TreeNode]);
            }
            if (data.hasOwnProperty('Parent')) {
                obj['Parent'] = TreeNode.constructFromObject(data['Parent']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TreeNode>} Children
 */
RestNodesCollection.prototype['Children'] = undefined;

/**
 * @member {module:model/TreeNode} Parent
 */
RestNodesCollection.prototype['Parent'] = undefined;






export default RestNodesCollection;

