/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RestBackgroundJobResult from './RestBackgroundJobResult';

/**
 * The RestRestoreNodesResponse model module.
 * @module model/RestRestoreNodesResponse
 * @version 4.0
 */
class RestRestoreNodesResponse {
    /**
     * Constructs a new <code>RestRestoreNodesResponse</code>.
     * @alias module:model/RestRestoreNodesResponse
     */
    constructor() { 
        
        RestRestoreNodesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestRestoreNodesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestRestoreNodesResponse} obj Optional instance to populate.
     * @return {module:model/RestRestoreNodesResponse} The populated <code>RestRestoreNodesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestRestoreNodesResponse();

            if (data.hasOwnProperty('RestoreJobs')) {
                obj['RestoreJobs'] = ApiClient.convertToType(data['RestoreJobs'], [RestBackgroundJobResult]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/RestBackgroundJobResult>} RestoreJobs
 */
RestRestoreNodesResponse.prototype['RestoreJobs'] = undefined;






export default RestRestoreNodesResponse;

