/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmACL from './IdmACL';

/**
 * The RestACLCollection model module.
 * @module model/RestACLCollection
 * @version 4.0
 */
class RestACLCollection {
    /**
     * Constructs a new <code>RestACLCollection</code>.
     * @alias module:model/RestACLCollection
     */
    constructor() { 
        
        RestACLCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestACLCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestACLCollection} obj Optional instance to populate.
     * @return {module:model/RestACLCollection} The populated <code>RestACLCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestACLCollection();

            if (data.hasOwnProperty('ACLs')) {
                obj['ACLs'] = ApiClient.convertToType(data['ACLs'], [IdmACL]);
            }
            if (data.hasOwnProperty('Total')) {
                obj['Total'] = ApiClient.convertToType(data['Total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/IdmACL>} ACLs
 */
RestACLCollection.prototype['ACLs'] = undefined;

/**
 * @member {Number} Total
 */
RestACLCollection.prototype['Total'] = undefined;






export default RestACLCollection;

