/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestActionDescription model module.
 * @module model/RestActionDescription
 * @version 4.0
 */
class RestActionDescription {
    /**
     * Constructs a new <code>RestActionDescription</code>.
     * @alias module:model/RestActionDescription
     */
    constructor() { 
        
        RestActionDescription.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestActionDescription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestActionDescription} obj Optional instance to populate.
     * @return {module:model/RestActionDescription} The populated <code>RestActionDescription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestActionDescription();

            if (data.hasOwnProperty('Category')) {
                obj['Category'] = ApiClient.convertToType(data['Category'], 'String');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('FormModule')) {
                obj['FormModule'] = ApiClient.convertToType(data['FormModule'], 'String');
            }
            if (data.hasOwnProperty('FormModuleProps')) {
                obj['FormModuleProps'] = ApiClient.convertToType(data['FormModuleProps'], 'String');
            }
            if (data.hasOwnProperty('HasForm')) {
                obj['HasForm'] = ApiClient.convertToType(data['HasForm'], 'Boolean');
            }
            if (data.hasOwnProperty('Icon')) {
                obj['Icon'] = ApiClient.convertToType(data['Icon'], 'String');
            }
            if (data.hasOwnProperty('InputDescription')) {
                obj['InputDescription'] = ApiClient.convertToType(data['InputDescription'], 'String');
            }
            if (data.hasOwnProperty('IsInternal')) {
                obj['IsInternal'] = ApiClient.convertToType(data['IsInternal'], 'Boolean');
            }
            if (data.hasOwnProperty('Label')) {
                obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('OutputDescription')) {
                obj['OutputDescription'] = ApiClient.convertToType(data['OutputDescription'], 'String');
            }
            if (data.hasOwnProperty('SummaryTemplate')) {
                obj['SummaryTemplate'] = ApiClient.convertToType(data['SummaryTemplate'], 'String');
            }
            if (data.hasOwnProperty('Tint')) {
                obj['Tint'] = ApiClient.convertToType(data['Tint'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} Category
 */
RestActionDescription.prototype['Category'] = undefined;

/**
 * @member {String} Description
 */
RestActionDescription.prototype['Description'] = undefined;

/**
 * @member {String} FormModule
 */
RestActionDescription.prototype['FormModule'] = undefined;

/**
 * @member {String} FormModuleProps
 */
RestActionDescription.prototype['FormModuleProps'] = undefined;

/**
 * @member {Boolean} HasForm
 */
RestActionDescription.prototype['HasForm'] = undefined;

/**
 * @member {String} Icon
 */
RestActionDescription.prototype['Icon'] = undefined;

/**
 * @member {String} InputDescription
 */
RestActionDescription.prototype['InputDescription'] = undefined;

/**
 * If action is declared internal, it is hidden to avoid polluting the list.
 * @member {Boolean} IsInternal
 */
RestActionDescription.prototype['IsInternal'] = undefined;

/**
 * @member {String} Label
 */
RestActionDescription.prototype['Label'] = undefined;

/**
 * @member {String} Name
 */
RestActionDescription.prototype['Name'] = undefined;

/**
 * @member {String} OutputDescription
 */
RestActionDescription.prototype['OutputDescription'] = undefined;

/**
 * @member {String} SummaryTemplate
 */
RestActionDescription.prototype['SummaryTemplate'] = undefined;

/**
 * @member {String} Tint
 */
RestActionDescription.prototype['Tint'] = undefined;






export default RestActionDescription;

