/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RestComponentStatus from './RestComponentStatus';

/**
 * The RestHealthServiceResponse model module.
 * @module model/RestHealthServiceResponse
 * @version 4.0
 */
class RestHealthServiceResponse {
    /**
     * Constructs a new <code>RestHealthServiceResponse</code>.
     * @alias module:model/RestHealthServiceResponse
     */
    constructor() { 
        
        RestHealthServiceResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestHealthServiceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestHealthServiceResponse} obj Optional instance to populate.
     * @return {module:model/RestHealthServiceResponse} The populated <code>RestHealthServiceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestHealthServiceResponse();

            if (data.hasOwnProperty('Components')) {
                obj['Components'] = ApiClient.convertToType(data['Components'], {'String': RestComponentStatus});
            }
            if (data.hasOwnProperty('Status')) {
                obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestHealthServiceResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestHealthServiceResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Status'] && !(typeof data['Status'] === 'string' || data['Status'] instanceof String)) {
            throw new Error("Expected the field `Status` to be a primitive type in the JSON string but got " + data['Status']);
        }

        return true;
    }


}



/**
 * @member {Object.<String, module:model/RestComponentStatus>} Components
 */
RestHealthServiceResponse.prototype['Components'] = undefined;

/**
 * @member {String} Status
 */
RestHealthServiceResponse.prototype['Status'] = undefined;






export default RestHealthServiceResponse;

