/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RestSettingsAccessRestPolicy from './RestSettingsAccessRestPolicy';

/**
 * The RestSettingsAccess model module.
 * @module model/RestSettingsAccess
 * @version 4.0
 */
class RestSettingsAccess {
    /**
     * Constructs a new <code>RestSettingsAccess</code>.
     * @alias module:model/RestSettingsAccess
     */
    constructor() { 
        
        RestSettingsAccess.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestSettingsAccess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestSettingsAccess} obj Optional instance to populate.
     * @return {module:model/RestSettingsAccess} The populated <code>RestSettingsAccess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestSettingsAccess();

            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('Label')) {
                obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
            }
            if (data.hasOwnProperty('Policies')) {
                obj['Policies'] = ApiClient.convertToType(data['Policies'], [RestSettingsAccessRestPolicy]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestSettingsAccess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestSettingsAccess</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Description'] && !(typeof data['Description'] === 'string' || data['Description'] instanceof String)) {
            throw new Error("Expected the field `Description` to be a primitive type in the JSON string but got " + data['Description']);
        }
        // ensure the json data is a string
        if (data['Label'] && !(typeof data['Label'] === 'string' || data['Label'] instanceof String)) {
            throw new Error("Expected the field `Label` to be a primitive type in the JSON string but got " + data['Label']);
        }
        if (data['Policies']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Policies'])) {
                throw new Error("Expected the field `Policies` to be an array in the JSON data but got " + data['Policies']);
            }
            // validate the optional field `Policies` (array)
            for (const item of data['Policies']) {
                RestSettingsAccessRestPolicy.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} Description
 */
RestSettingsAccess.prototype['Description'] = undefined;

/**
 * @member {String} Label
 */
RestSettingsAccess.prototype['Label'] = undefined;

/**
 * @member {Array.<module:model/RestSettingsAccessRestPolicy>} Policies
 */
RestSettingsAccess.prototype['Policies'] = undefined;






export default RestSettingsAccess;

