/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestResetPasswordRequest model module.
 * @module model/RestResetPasswordRequest
 * @version 4.0
 */
class RestResetPasswordRequest {
    /**
     * Constructs a new <code>RestResetPasswordRequest</code>.
     * @alias module:model/RestResetPasswordRequest
     */
    constructor() { 
        
        RestResetPasswordRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestResetPasswordRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestResetPasswordRequest} obj Optional instance to populate.
     * @return {module:model/RestResetPasswordRequest} The populated <code>RestResetPasswordRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestResetPasswordRequest();

            if (data.hasOwnProperty('NewPassword')) {
                obj['NewPassword'] = ApiClient.convertToType(data['NewPassword'], 'String');
            }
            if (data.hasOwnProperty('ResetPasswordToken')) {
                obj['ResetPasswordToken'] = ApiClient.convertToType(data['ResetPasswordToken'], 'String');
            }
            if (data.hasOwnProperty('UserLogin')) {
                obj['UserLogin'] = ApiClient.convertToType(data['UserLogin'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} NewPassword
 */
RestResetPasswordRequest.prototype['NewPassword'] = undefined;

/**
 * @member {String} ResetPasswordToken
 */
RestResetPasswordRequest.prototype['ResetPasswordToken'] = undefined;

/**
 * @member {String} UserLogin
 */
RestResetPasswordRequest.prototype['UserLogin'] = undefined;






export default RestResetPasswordRequest;

