/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestOpenApiResponse model module.
 * @module model/RestOpenApiResponse
 * @version 4.0
 */
class RestOpenApiResponse {
    /**
     * Constructs a new <code>RestOpenApiResponse</code>.
     * @alias module:model/RestOpenApiResponse
     */
    constructor() { 
        
        RestOpenApiResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestOpenApiResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestOpenApiResponse} obj Optional instance to populate.
     * @return {module:model/RestOpenApiResponse} The populated <code>RestOpenApiResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestOpenApiResponse();

            if (data.hasOwnProperty('Data')) {
                obj['Data'] = ApiClient.convertToType(data['Data'], 'Blob');
            }
        }
        return obj;
    }


}

/**
 * @member {Blob} Data
 */
RestOpenApiResponse.prototype['Data'] = undefined;






export default RestOpenApiResponse;

