/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestDiscoveryResponse model module.
 * @module model/RestDiscoveryResponse
 * @version 4.0
 */
class RestDiscoveryResponse {
    /**
     * Constructs a new <code>RestDiscoveryResponse</code>.
     * @alias module:model/RestDiscoveryResponse
     */
    constructor() { 
        
        RestDiscoveryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestDiscoveryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestDiscoveryResponse} obj Optional instance to populate.
     * @return {module:model/RestDiscoveryResponse} The populated <code>RestDiscoveryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestDiscoveryResponse();

            if (data.hasOwnProperty('BuildRevision')) {
                obj['BuildRevision'] = ApiClient.convertToType(data['BuildRevision'], 'String');
            }
            if (data.hasOwnProperty('BuildStamp')) {
                obj['BuildStamp'] = ApiClient.convertToType(data['BuildStamp'], 'Number');
            }
            if (data.hasOwnProperty('Endpoints')) {
                obj['Endpoints'] = ApiClient.convertToType(data['Endpoints'], {'String': 'String'});
            }
            if (data.hasOwnProperty('PackageLabel')) {
                obj['PackageLabel'] = ApiClient.convertToType(data['PackageLabel'], 'String');
            }
            if (data.hasOwnProperty('PackageType')) {
                obj['PackageType'] = ApiClient.convertToType(data['PackageType'], 'String');
            }
            if (data.hasOwnProperty('Version')) {
                obj['Version'] = ApiClient.convertToType(data['Version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} BuildRevision
 */
RestDiscoveryResponse.prototype['BuildRevision'] = undefined;

/**
 * @member {Number} BuildStamp
 */
RestDiscoveryResponse.prototype['BuildStamp'] = undefined;

/**
 * @member {Object.<String, String>} Endpoints
 */
RestDiscoveryResponse.prototype['Endpoints'] = undefined;

/**
 * @member {String} PackageLabel
 */
RestDiscoveryResponse.prototype['PackageLabel'] = undefined;

/**
 * @member {String} PackageType
 */
RestDiscoveryResponse.prototype['PackageType'] = undefined;

/**
 * @member {String} Version
 */
RestDiscoveryResponse.prototype['Version'] = undefined;






export default RestDiscoveryResponse;

