/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestCreateStorageBucketResponse model module.
 * @module model/RestCreateStorageBucketResponse
 * @version 4.0
 */
class RestCreateStorageBucketResponse {
    /**
     * Constructs a new <code>RestCreateStorageBucketResponse</code>.
     * @alias module:model/RestCreateStorageBucketResponse
     */
    constructor() { 
        
        RestCreateStorageBucketResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestCreateStorageBucketResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestCreateStorageBucketResponse} obj Optional instance to populate.
     * @return {module:model/RestCreateStorageBucketResponse} The populated <code>RestCreateStorageBucketResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestCreateStorageBucketResponse();

            if (data.hasOwnProperty('BucketName')) {
                obj['BucketName'] = ApiClient.convertToType(data['BucketName'], 'String');
            }
            if (data.hasOwnProperty('Success')) {
                obj['Success'] = ApiClient.convertToType(data['Success'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} BucketName
 */
RestCreateStorageBucketResponse.prototype['BucketName'] = undefined;

/**
 * @member {Boolean} Success
 */
RestCreateStorageBucketResponse.prototype['Success'] = undefined;






export default RestCreateStorageBucketResponse;

