/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestProcess model module.
 * @module model/RestProcess
 * @version 4.0
 */
class RestProcess {
    /**
     * Constructs a new <code>RestProcess</code>.
     * @alias module:model/RestProcess
     */
    constructor() { 
        
        RestProcess.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestProcess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestProcess} obj Optional instance to populate.
     * @return {module:model/RestProcess} The populated <code>RestProcess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestProcess();

            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
            }
            if (data.hasOwnProperty('MetricsPort')) {
                obj['MetricsPort'] = ApiClient.convertToType(data['MetricsPort'], 'Number');
            }
            if (data.hasOwnProperty('ParentID')) {
                obj['ParentID'] = ApiClient.convertToType(data['ParentID'], 'String');
            }
            if (data.hasOwnProperty('PeerAddress')) {
                obj['PeerAddress'] = ApiClient.convertToType(data['PeerAddress'], 'String');
            }
            if (data.hasOwnProperty('PeerId')) {
                obj['PeerId'] = ApiClient.convertToType(data['PeerId'], 'String');
            }
            if (data.hasOwnProperty('Services')) {
                obj['Services'] = ApiClient.convertToType(data['Services'], ['String']);
            }
            if (data.hasOwnProperty('StartTag')) {
                obj['StartTag'] = ApiClient.convertToType(data['StartTag'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestProcess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestProcess</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ID'] && !(typeof data['ID'] === 'string' || data['ID'] instanceof String)) {
            throw new Error("Expected the field `ID` to be a primitive type in the JSON string but got " + data['ID']);
        }
        // ensure the json data is a string
        if (data['ParentID'] && !(typeof data['ParentID'] === 'string' || data['ParentID'] instanceof String)) {
            throw new Error("Expected the field `ParentID` to be a primitive type in the JSON string but got " + data['ParentID']);
        }
        // ensure the json data is a string
        if (data['PeerAddress'] && !(typeof data['PeerAddress'] === 'string' || data['PeerAddress'] instanceof String)) {
            throw new Error("Expected the field `PeerAddress` to be a primitive type in the JSON string but got " + data['PeerAddress']);
        }
        // ensure the json data is a string
        if (data['PeerId'] && !(typeof data['PeerId'] === 'string' || data['PeerId'] instanceof String)) {
            throw new Error("Expected the field `PeerId` to be a primitive type in the JSON string but got " + data['PeerId']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['Services'])) {
            throw new Error("Expected the field `Services` to be an array in the JSON data but got " + data['Services']);
        }
        // ensure the json data is a string
        if (data['StartTag'] && !(typeof data['StartTag'] === 'string' || data['StartTag'] instanceof String)) {
            throw new Error("Expected the field `StartTag` to be a primitive type in the JSON string but got " + data['StartTag']);
        }

        return true;
    }


}



/**
 * @member {String} ID
 */
RestProcess.prototype['ID'] = undefined;

/**
 * @member {Number} MetricsPort
 */
RestProcess.prototype['MetricsPort'] = undefined;

/**
 * @member {String} ParentID
 */
RestProcess.prototype['ParentID'] = undefined;

/**
 * @member {String} PeerAddress
 */
RestProcess.prototype['PeerAddress'] = undefined;

/**
 * @member {String} PeerId
 */
RestProcess.prototype['PeerId'] = undefined;

/**
 * @member {Array.<String>} Services
 */
RestProcess.prototype['Services'] = undefined;

/**
 * @member {String} StartTag
 */
RestProcess.prototype['StartTag'] = undefined;






export default RestProcess;

