/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenServiceResetPasswordTokenBody model module.
 * @module model/TokenServiceResetPasswordTokenBody
 * @version 4.0
 */
class TokenServiceResetPasswordTokenBody {
    /**
     * Constructs a new <code>TokenServiceResetPasswordTokenBody</code>.
     * @alias module:model/TokenServiceResetPasswordTokenBody
     */
    constructor() { 
        
        TokenServiceResetPasswordTokenBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TokenServiceResetPasswordTokenBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenServiceResetPasswordTokenBody} obj Optional instance to populate.
     * @return {module:model/TokenServiceResetPasswordTokenBody} The populated <code>TokenServiceResetPasswordTokenBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenServiceResetPasswordTokenBody();

            if (data.hasOwnProperty('Create')) {
                obj['Create'] = ApiClient.convertToType(data['Create'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenServiceResetPasswordTokenBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenServiceResetPasswordTokenBody</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} Create
 */
TokenServiceResetPasswordTokenBody.prototype['Create'] = undefined;






export default TokenServiceResetPasswordTokenBody;

