/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TreeGeoPoint model module.
 * @module model/TreeGeoPoint
 * @version 4.0
 */
class TreeGeoPoint {
    /**
     * Constructs a new <code>TreeGeoPoint</code>.
     * @alias module:model/TreeGeoPoint
     */
    constructor() { 
        
        TreeGeoPoint.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TreeGeoPoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TreeGeoPoint} obj Optional instance to populate.
     * @return {module:model/TreeGeoPoint} The populated <code>TreeGeoPoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TreeGeoPoint();

            if (data.hasOwnProperty('Lat')) {
                obj['Lat'] = ApiClient.convertToType(data['Lat'], 'Number');
            }
            if (data.hasOwnProperty('Lon')) {
                obj['Lon'] = ApiClient.convertToType(data['Lon'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} Lat
 */
TreeGeoPoint.prototype['Lat'] = undefined;

/**
 * @member {Number} Lon
 */
TreeGeoPoint.prototype['Lon'] = undefined;






export default TreeGeoPoint;

