"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The IdmPolicySubject model module.
 * @module model/IdmPolicySubject
 * @version 4.0
 */
var IdmPolicySubject = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>IdmPolicySubject</code>.
   * @alias module:model/IdmPolicySubject
   */
  function IdmPolicySubject() {
    _classCallCheck(this, IdmPolicySubject);
    IdmPolicySubject.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(IdmPolicySubject, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>IdmPolicySubject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmPolicySubject} obj Optional instance to populate.
     * @return {module:model/IdmPolicySubject} The populated <code>IdmPolicySubject</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new IdmPolicySubject();
        if (data.hasOwnProperty('Compiled')) {
          obj['Compiled'] = _ApiClient["default"].convertToType(data['Compiled'], 'String');
        }
        if (data.hasOwnProperty('HasRegex')) {
          obj['HasRegex'] = _ApiClient["default"].convertToType(data['HasRegex'], 'Boolean');
        }
        if (data.hasOwnProperty('ID')) {
          obj['ID'] = _ApiClient["default"].convertToType(data['ID'], 'String');
        }
        if (data.hasOwnProperty('Template')) {
          obj['Template'] = _ApiClient["default"].convertToType(data['Template'], 'String');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmPolicySubject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmPolicySubject</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is a string
      if (data['Compiled'] && !(typeof data['Compiled'] === 'string' || data['Compiled'] instanceof String)) {
        throw new Error("Expected the field `Compiled` to be a primitive type in the JSON string but got " + data['Compiled']);
      }
      // ensure the json data is a string
      if (data['ID'] && !(typeof data['ID'] === 'string' || data['ID'] instanceof String)) {
        throw new Error("Expected the field `ID` to be a primitive type in the JSON string but got " + data['ID']);
      }
      // ensure the json data is a string
      if (data['Template'] && !(typeof data['Template'] === 'string' || data['Template'] instanceof String)) {
        throw new Error("Expected the field `Template` to be a primitive type in the JSON string but got " + data['Template']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {String} Compiled
 */
IdmPolicySubject.prototype['Compiled'] = undefined;

/**
 * @member {Boolean} HasRegex
 */
IdmPolicySubject.prototype['HasRegex'] = undefined;

/**
 * @member {String} ID
 */
IdmPolicySubject.prototype['ID'] = undefined;

/**
 * @member {String} Template
 */
IdmPolicySubject.prototype['Template'] = undefined;
var _default = exports["default"] = IdmPolicySubject;
//# sourceMappingURL=IdmPolicySubject.js.map
