"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _IdmWorkspaceScope = _interopRequireDefault(require("./IdmWorkspaceScope"));
var _ServiceResourcePolicy = _interopRequireDefault(require("./ServiceResourcePolicy"));
var _TreeNode = _interopRequireDefault(require("./TreeNode"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _createForOfIteratorHelper(r, e) { var t = "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (!t) { if (Array.isArray(r) || (t = _unsupportedIterableToArray(r)) || e && r && "number" == typeof r.length) { t && (r = t); var _n = 0, F = function F() {}; return { s: F, n: function n() { return _n >= r.length ? { done: !0 } : { done: !1, value: r[_n++] }; }, e: function e(r) { throw r; }, f: F }; } throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); } var o, a = !0, u = !1; return { s: function s() { t = t.call(r); }, n: function n() { var r = t.next(); return a = r.done, r; }, e: function e(r) { u = !0, o = r; }, f: function f() { try { a || null == t["return"] || t["return"](); } finally { if (u) throw o; } } }; }
function _unsupportedIterableToArray(r, a) { if (r) { if ("string" == typeof r) return _arrayLikeToArray(r, a); var t = {}.toString.call(r).slice(8, -1); return "Object" === t && r.constructor && (t = r.constructor.name), "Map" === t || "Set" === t ? Array.from(r) : "Arguments" === t || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t) ? _arrayLikeToArray(r, a) : void 0; } }
function _arrayLikeToArray(r, a) { (null == a || a > r.length) && (a = r.length); for (var e = 0, n = Array(a); e < a; e++) n[e] = r[e]; return n; }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The IdmWorkspace model module.
 * @module model/IdmWorkspace
 * @version 4.0
 */
var IdmWorkspace = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>IdmWorkspace</code>.
   * A Workspace is composed of a set of nodes UUIDs and is used to provide accesses to the tree via ACLs.
   * @alias module:model/IdmWorkspace
   */
  function IdmWorkspace() {
    _classCallCheck(this, IdmWorkspace);
    IdmWorkspace.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(IdmWorkspace, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>IdmWorkspace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmWorkspace} obj Optional instance to populate.
     * @return {module:model/IdmWorkspace} The populated <code>IdmWorkspace</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new IdmWorkspace();
        if (data.hasOwnProperty('Attributes')) {
          obj['Attributes'] = _ApiClient["default"].convertToType(data['Attributes'], 'String');
        }
        if (data.hasOwnProperty('Description')) {
          obj['Description'] = _ApiClient["default"].convertToType(data['Description'], 'String');
        }
        if (data.hasOwnProperty('Label')) {
          obj['Label'] = _ApiClient["default"].convertToType(data['Label'], 'String');
        }
        if (data.hasOwnProperty('LastUpdated')) {
          obj['LastUpdated'] = _ApiClient["default"].convertToType(data['LastUpdated'], 'Number');
        }
        if (data.hasOwnProperty('Policies')) {
          obj['Policies'] = _ApiClient["default"].convertToType(data['Policies'], [_ServiceResourcePolicy["default"]]);
        }
        if (data.hasOwnProperty('PoliciesContextEditable')) {
          obj['PoliciesContextEditable'] = _ApiClient["default"].convertToType(data['PoliciesContextEditable'], 'Boolean');
        }
        if (data.hasOwnProperty('RootNodes')) {
          obj['RootNodes'] = _ApiClient["default"].convertToType(data['RootNodes'], {
            'String': _TreeNode["default"]
          });
        }
        if (data.hasOwnProperty('RootUUIDs')) {
          obj['RootUUIDs'] = _ApiClient["default"].convertToType(data['RootUUIDs'], ['String']);
        }
        if (data.hasOwnProperty('Scope')) {
          obj['Scope'] = _IdmWorkspaceScope["default"].constructFromObject(data['Scope']);
        }
        if (data.hasOwnProperty('Slug')) {
          obj['Slug'] = _ApiClient["default"].convertToType(data['Slug'], 'String');
        }
        if (data.hasOwnProperty('UUID')) {
          obj['UUID'] = _ApiClient["default"].convertToType(data['UUID'], 'String');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmWorkspace</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmWorkspace</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is a string
      if (data['Attributes'] && !(typeof data['Attributes'] === 'string' || data['Attributes'] instanceof String)) {
        throw new Error("Expected the field `Attributes` to be a primitive type in the JSON string but got " + data['Attributes']);
      }
      // ensure the json data is a string
      if (data['Description'] && !(typeof data['Description'] === 'string' || data['Description'] instanceof String)) {
        throw new Error("Expected the field `Description` to be a primitive type in the JSON string but got " + data['Description']);
      }
      // ensure the json data is a string
      if (data['Label'] && !(typeof data['Label'] === 'string' || data['Label'] instanceof String)) {
        throw new Error("Expected the field `Label` to be a primitive type in the JSON string but got " + data['Label']);
      }
      if (data['Policies']) {
        // data not null
        // ensure the json data is an array
        if (!Array.isArray(data['Policies'])) {
          throw new Error("Expected the field `Policies` to be an array in the JSON data but got " + data['Policies']);
        }
        // validate the optional field `Policies` (array)
        var _iterator = _createForOfIteratorHelper(data['Policies']),
          _step;
        try {
          for (_iterator.s(); !(_step = _iterator.n()).done;) {
            var item = _step.value;
            _ServiceResourcePolicy["default"].validateJSON(item);
          }
        } catch (err) {
          _iterator.e(err);
        } finally {
          _iterator.f();
        }
        ;
      }
      // ensure the json data is an array
      if (!Array.isArray(data['RootUUIDs'])) {
        throw new Error("Expected the field `RootUUIDs` to be an array in the JSON data but got " + data['RootUUIDs']);
      }
      // ensure the json data is a string
      if (data['Slug'] && !(typeof data['Slug'] === 'string' || data['Slug'] instanceof String)) {
        throw new Error("Expected the field `Slug` to be a primitive type in the JSON string but got " + data['Slug']);
      }
      // ensure the json data is a string
      if (data['UUID'] && !(typeof data['UUID'] === 'string' || data['UUID'] instanceof String)) {
        throw new Error("Expected the field `UUID` to be a primitive type in the JSON string but got " + data['UUID']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {String} Attributes
 */
IdmWorkspace.prototype['Attributes'] = undefined;

/**
 * @member {String} Description
 */
IdmWorkspace.prototype['Description'] = undefined;

/**
 * @member {String} Label
 */
IdmWorkspace.prototype['Label'] = undefined;

/**
 * @member {Number} LastUpdated
 */
IdmWorkspace.prototype['LastUpdated'] = undefined;

/**
 * @member {Array.<module:model/ServiceResourcePolicy>} Policies
 */
IdmWorkspace.prototype['Policies'] = undefined;

/**
 * @member {Boolean} PoliciesContextEditable
 */
IdmWorkspace.prototype['PoliciesContextEditable'] = undefined;

/**
 * @member {Object.<String, module:model/TreeNode>} RootNodes
 */
IdmWorkspace.prototype['RootNodes'] = undefined;

/**
 * @member {Array.<String>} RootUUIDs
 */
IdmWorkspace.prototype['RootUUIDs'] = undefined;

/**
 * @member {module:model/IdmWorkspaceScope} Scope
 */
IdmWorkspace.prototype['Scope'] = undefined;

/**
 * @member {String} Slug
 */
IdmWorkspace.prototype['Slug'] = undefined;

/**
 * @member {String} UUID
 */
IdmWorkspace.prototype['UUID'] = undefined;
var _default = exports["default"] = IdmWorkspace;
//# sourceMappingURL=IdmWorkspace.js.map
