"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _InstallCheckResult = _interopRequireDefault(require("./InstallCheckResult"));
var _InstallProxyConfig = _interopRequireDefault(require("./InstallProxyConfig"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _createForOfIteratorHelper(r, e) { var t = "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (!t) { if (Array.isArray(r) || (t = _unsupportedIterableToArray(r)) || e && r && "number" == typeof r.length) { t && (r = t); var _n = 0, F = function F() {}; return { s: F, n: function n() { return _n >= r.length ? { done: !0 } : { done: !1, value: r[_n++] }; }, e: function e(r) { throw r; }, f: F }; } throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); } var o, a = !0, u = !1; return { s: function s() { t = t.call(r); }, n: function n() { var r = t.next(); return a = r.done, r; }, e: function e(r) { u = !0, o = r; }, f: function f() { try { a || null == t["return"] || t["return"](); } finally { if (u) throw o; } } }; }
function _unsupportedIterableToArray(r, a) { if (r) { if ("string" == typeof r) return _arrayLikeToArray(r, a); var t = {}.toString.call(r).slice(8, -1); return "Object" === t && r.constructor && (t = r.constructor.name), "Map" === t || "Set" === t ? Array.from(r) : "Arguments" === t || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t) ? _arrayLikeToArray(r, a) : void 0; } }
function _arrayLikeToArray(r, a) { (null == a || a > r.length) && (a = r.length); for (var e = 0, n = Array(a); e < a; e++) n[e] = r[e]; return n; }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The InstallInstallConfig model module.
 * @module model/InstallInstallConfig
 * @version 4.0
 */
var InstallInstallConfig = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>InstallInstallConfig</code>.
   * @alias module:model/InstallInstallConfig
   */
  function InstallInstallConfig() {
    _classCallCheck(this, InstallInstallConfig);
    InstallInstallConfig.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(InstallInstallConfig, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>InstallInstallConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstallInstallConfig} obj Optional instance to populate.
     * @return {module:model/InstallInstallConfig} The populated <code>InstallInstallConfig</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new InstallInstallConfig();
        if (data.hasOwnProperty('CheckResults')) {
          obj['CheckResults'] = _ApiClient["default"].convertToType(data['CheckResults'], [_InstallCheckResult["default"]]);
        }
        if (data.hasOwnProperty('CustomConfigs')) {
          obj['CustomConfigs'] = _ApiClient["default"].convertToType(data['CustomConfigs'], {
            'String': 'String'
          });
        }
        if (data.hasOwnProperty('DocumentsDSN')) {
          obj['DocumentsDSN'] = _ApiClient["default"].convertToType(data['DocumentsDSN'], 'String');
        }
        if (data.hasOwnProperty('ProxyConfig')) {
          obj['ProxyConfig'] = _InstallProxyConfig["default"].constructFromObject(data['ProxyConfig']);
        }
        if (data.hasOwnProperty('UseDocumentsDSN')) {
          obj['UseDocumentsDSN'] = _ApiClient["default"].convertToType(data['UseDocumentsDSN'], 'Boolean');
        }
        if (data.hasOwnProperty('dbConnectionType')) {
          obj['dbConnectionType'] = _ApiClient["default"].convertToType(data['dbConnectionType'], 'String');
        }
        if (data.hasOwnProperty('dbManualDSN')) {
          obj['dbManualDSN'] = _ApiClient["default"].convertToType(data['dbManualDSN'], 'String');
        }
        if (data.hasOwnProperty('dbSocketFile')) {
          obj['dbSocketFile'] = _ApiClient["default"].convertToType(data['dbSocketFile'], 'String');
        }
        if (data.hasOwnProperty('dbSocketName')) {
          obj['dbSocketName'] = _ApiClient["default"].convertToType(data['dbSocketName'], 'String');
        }
        if (data.hasOwnProperty('dbSocketPassword')) {
          obj['dbSocketPassword'] = _ApiClient["default"].convertToType(data['dbSocketPassword'], 'String');
        }
        if (data.hasOwnProperty('dbSocketUser')) {
          obj['dbSocketUser'] = _ApiClient["default"].convertToType(data['dbSocketUser'], 'String');
        }
        if (data.hasOwnProperty('dbTCPHostname')) {
          obj['dbTCPHostname'] = _ApiClient["default"].convertToType(data['dbTCPHostname'], 'String');
        }
        if (data.hasOwnProperty('dbTCPName')) {
          obj['dbTCPName'] = _ApiClient["default"].convertToType(data['dbTCPName'], 'String');
        }
        if (data.hasOwnProperty('dbTCPPassword')) {
          obj['dbTCPPassword'] = _ApiClient["default"].convertToType(data['dbTCPPassword'], 'String');
        }
        if (data.hasOwnProperty('dbTCPPort')) {
          obj['dbTCPPort'] = _ApiClient["default"].convertToType(data['dbTCPPort'], 'String');
        }
        if (data.hasOwnProperty('dbTCPUser')) {
          obj['dbTCPUser'] = _ApiClient["default"].convertToType(data['dbTCPUser'], 'String');
        }
        if (data.hasOwnProperty('dbUseDefaults')) {
          obj['dbUseDefaults'] = _ApiClient["default"].convertToType(data['dbUseDefaults'], 'Boolean');
        }
        if (data.hasOwnProperty('dsFolder')) {
          obj['dsFolder'] = _ApiClient["default"].convertToType(data['dsFolder'], 'String');
        }
        if (data.hasOwnProperty('dsName')) {
          obj['dsName'] = _ApiClient["default"].convertToType(data['dsName'], 'String');
        }
        if (data.hasOwnProperty('dsPort')) {
          obj['dsPort'] = _ApiClient["default"].convertToType(data['dsPort'], 'String');
        }
        if (data.hasOwnProperty('dsS3ApiKey')) {
          obj['dsS3ApiKey'] = _ApiClient["default"].convertToType(data['dsS3ApiKey'], 'String');
        }
        if (data.hasOwnProperty('dsS3ApiSecret')) {
          obj['dsS3ApiSecret'] = _ApiClient["default"].convertToType(data['dsS3ApiSecret'], 'String');
        }
        if (data.hasOwnProperty('dsS3BucketBinaries')) {
          obj['dsS3BucketBinaries'] = _ApiClient["default"].convertToType(data['dsS3BucketBinaries'], 'String');
        }
        if (data.hasOwnProperty('dsS3BucketCells')) {
          obj['dsS3BucketCells'] = _ApiClient["default"].convertToType(data['dsS3BucketCells'], 'String');
        }
        if (data.hasOwnProperty('dsS3BucketDefault')) {
          obj['dsS3BucketDefault'] = _ApiClient["default"].convertToType(data['dsS3BucketDefault'], 'String');
        }
        if (data.hasOwnProperty('dsS3BucketPersonal')) {
          obj['dsS3BucketPersonal'] = _ApiClient["default"].convertToType(data['dsS3BucketPersonal'], 'String');
        }
        if (data.hasOwnProperty('dsS3BucketThumbs')) {
          obj['dsS3BucketThumbs'] = _ApiClient["default"].convertToType(data['dsS3BucketThumbs'], 'String');
        }
        if (data.hasOwnProperty('dsS3BucketVersions')) {
          obj['dsS3BucketVersions'] = _ApiClient["default"].convertToType(data['dsS3BucketVersions'], 'String');
        }
        if (data.hasOwnProperty('dsS3Custom')) {
          obj['dsS3Custom'] = _ApiClient["default"].convertToType(data['dsS3Custom'], 'String');
        }
        if (data.hasOwnProperty('dsS3CustomRegion')) {
          obj['dsS3CustomRegion'] = _ApiClient["default"].convertToType(data['dsS3CustomRegion'], 'String');
        }
        if (data.hasOwnProperty('dsType')) {
          obj['dsType'] = _ApiClient["default"].convertToType(data['dsType'], 'String');
        }
        if (data.hasOwnProperty('frontendApplicationTitle')) {
          obj['frontendApplicationTitle'] = _ApiClient["default"].convertToType(data['frontendApplicationTitle'], 'String');
        }
        if (data.hasOwnProperty('frontendDefaultLanguage')) {
          obj['frontendDefaultLanguage'] = _ApiClient["default"].convertToType(data['frontendDefaultLanguage'], 'String');
        }
        if (data.hasOwnProperty('frontendHosts')) {
          obj['frontendHosts'] = _ApiClient["default"].convertToType(data['frontendHosts'], 'String');
        }
        if (data.hasOwnProperty('frontendLogin')) {
          obj['frontendLogin'] = _ApiClient["default"].convertToType(data['frontendLogin'], 'String');
        }
        if (data.hasOwnProperty('frontendPassword')) {
          obj['frontendPassword'] = _ApiClient["default"].convertToType(data['frontendPassword'], 'String');
        }
        if (data.hasOwnProperty('frontendRepeatPassword')) {
          obj['frontendRepeatPassword'] = _ApiClient["default"].convertToType(data['frontendRepeatPassword'], 'String');
        }
        if (data.hasOwnProperty('internalUrl')) {
          obj['internalUrl'] = _ApiClient["default"].convertToType(data['internalUrl'], 'String');
        }
        if (data.hasOwnProperty('licenseRequired')) {
          obj['licenseRequired'] = _ApiClient["default"].convertToType(data['licenseRequired'], 'Boolean');
        }
        if (data.hasOwnProperty('licenseString')) {
          obj['licenseString'] = _ApiClient["default"].convertToType(data['licenseString'], 'String');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstallInstallConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstallInstallConfig</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      if (data['CheckResults']) {
        // data not null
        // ensure the json data is an array
        if (!Array.isArray(data['CheckResults'])) {
          throw new Error("Expected the field `CheckResults` to be an array in the JSON data but got " + data['CheckResults']);
        }
        // validate the optional field `CheckResults` (array)
        var _iterator = _createForOfIteratorHelper(data['CheckResults']),
          _step;
        try {
          for (_iterator.s(); !(_step = _iterator.n()).done;) {
            var item = _step.value;
            _InstallCheckResult["default"].validateJSON(item);
          }
        } catch (err) {
          _iterator.e(err);
        } finally {
          _iterator.f();
        }
        ;
      }
      // ensure the json data is a string
      if (data['DocumentsDSN'] && !(typeof data['DocumentsDSN'] === 'string' || data['DocumentsDSN'] instanceof String)) {
        throw new Error("Expected the field `DocumentsDSN` to be a primitive type in the JSON string but got " + data['DocumentsDSN']);
      }
      // validate the optional field `ProxyConfig`
      if (data['ProxyConfig']) {
        // data not null
        _InstallProxyConfig["default"].validateJSON(data['ProxyConfig']);
      }
      // ensure the json data is a string
      if (data['dbConnectionType'] && !(typeof data['dbConnectionType'] === 'string' || data['dbConnectionType'] instanceof String)) {
        throw new Error("Expected the field `dbConnectionType` to be a primitive type in the JSON string but got " + data['dbConnectionType']);
      }
      // ensure the json data is a string
      if (data['dbManualDSN'] && !(typeof data['dbManualDSN'] === 'string' || data['dbManualDSN'] instanceof String)) {
        throw new Error("Expected the field `dbManualDSN` to be a primitive type in the JSON string but got " + data['dbManualDSN']);
      }
      // ensure the json data is a string
      if (data['dbSocketFile'] && !(typeof data['dbSocketFile'] === 'string' || data['dbSocketFile'] instanceof String)) {
        throw new Error("Expected the field `dbSocketFile` to be a primitive type in the JSON string but got " + data['dbSocketFile']);
      }
      // ensure the json data is a string
      if (data['dbSocketName'] && !(typeof data['dbSocketName'] === 'string' || data['dbSocketName'] instanceof String)) {
        throw new Error("Expected the field `dbSocketName` to be a primitive type in the JSON string but got " + data['dbSocketName']);
      }
      // ensure the json data is a string
      if (data['dbSocketPassword'] && !(typeof data['dbSocketPassword'] === 'string' || data['dbSocketPassword'] instanceof String)) {
        throw new Error("Expected the field `dbSocketPassword` to be a primitive type in the JSON string but got " + data['dbSocketPassword']);
      }
      // ensure the json data is a string
      if (data['dbSocketUser'] && !(typeof data['dbSocketUser'] === 'string' || data['dbSocketUser'] instanceof String)) {
        throw new Error("Expected the field `dbSocketUser` to be a primitive type in the JSON string but got " + data['dbSocketUser']);
      }
      // ensure the json data is a string
      if (data['dbTCPHostname'] && !(typeof data['dbTCPHostname'] === 'string' || data['dbTCPHostname'] instanceof String)) {
        throw new Error("Expected the field `dbTCPHostname` to be a primitive type in the JSON string but got " + data['dbTCPHostname']);
      }
      // ensure the json data is a string
      if (data['dbTCPName'] && !(typeof data['dbTCPName'] === 'string' || data['dbTCPName'] instanceof String)) {
        throw new Error("Expected the field `dbTCPName` to be a primitive type in the JSON string but got " + data['dbTCPName']);
      }
      // ensure the json data is a string
      if (data['dbTCPPassword'] && !(typeof data['dbTCPPassword'] === 'string' || data['dbTCPPassword'] instanceof String)) {
        throw new Error("Expected the field `dbTCPPassword` to be a primitive type in the JSON string but got " + data['dbTCPPassword']);
      }
      // ensure the json data is a string
      if (data['dbTCPPort'] && !(typeof data['dbTCPPort'] === 'string' || data['dbTCPPort'] instanceof String)) {
        throw new Error("Expected the field `dbTCPPort` to be a primitive type in the JSON string but got " + data['dbTCPPort']);
      }
      // ensure the json data is a string
      if (data['dbTCPUser'] && !(typeof data['dbTCPUser'] === 'string' || data['dbTCPUser'] instanceof String)) {
        throw new Error("Expected the field `dbTCPUser` to be a primitive type in the JSON string but got " + data['dbTCPUser']);
      }
      // ensure the json data is a string
      if (data['dsFolder'] && !(typeof data['dsFolder'] === 'string' || data['dsFolder'] instanceof String)) {
        throw new Error("Expected the field `dsFolder` to be a primitive type in the JSON string but got " + data['dsFolder']);
      }
      // ensure the json data is a string
      if (data['dsName'] && !(typeof data['dsName'] === 'string' || data['dsName'] instanceof String)) {
        throw new Error("Expected the field `dsName` to be a primitive type in the JSON string but got " + data['dsName']);
      }
      // ensure the json data is a string
      if (data['dsPort'] && !(typeof data['dsPort'] === 'string' || data['dsPort'] instanceof String)) {
        throw new Error("Expected the field `dsPort` to be a primitive type in the JSON string but got " + data['dsPort']);
      }
      // ensure the json data is a string
      if (data['dsS3ApiKey'] && !(typeof data['dsS3ApiKey'] === 'string' || data['dsS3ApiKey'] instanceof String)) {
        throw new Error("Expected the field `dsS3ApiKey` to be a primitive type in the JSON string but got " + data['dsS3ApiKey']);
      }
      // ensure the json data is a string
      if (data['dsS3ApiSecret'] && !(typeof data['dsS3ApiSecret'] === 'string' || data['dsS3ApiSecret'] instanceof String)) {
        throw new Error("Expected the field `dsS3ApiSecret` to be a primitive type in the JSON string but got " + data['dsS3ApiSecret']);
      }
      // ensure the json data is a string
      if (data['dsS3BucketBinaries'] && !(typeof data['dsS3BucketBinaries'] === 'string' || data['dsS3BucketBinaries'] instanceof String)) {
        throw new Error("Expected the field `dsS3BucketBinaries` to be a primitive type in the JSON string but got " + data['dsS3BucketBinaries']);
      }
      // ensure the json data is a string
      if (data['dsS3BucketCells'] && !(typeof data['dsS3BucketCells'] === 'string' || data['dsS3BucketCells'] instanceof String)) {
        throw new Error("Expected the field `dsS3BucketCells` to be a primitive type in the JSON string but got " + data['dsS3BucketCells']);
      }
      // ensure the json data is a string
      if (data['dsS3BucketDefault'] && !(typeof data['dsS3BucketDefault'] === 'string' || data['dsS3BucketDefault'] instanceof String)) {
        throw new Error("Expected the field `dsS3BucketDefault` to be a primitive type in the JSON string but got " + data['dsS3BucketDefault']);
      }
      // ensure the json data is a string
      if (data['dsS3BucketPersonal'] && !(typeof data['dsS3BucketPersonal'] === 'string' || data['dsS3BucketPersonal'] instanceof String)) {
        throw new Error("Expected the field `dsS3BucketPersonal` to be a primitive type in the JSON string but got " + data['dsS3BucketPersonal']);
      }
      // ensure the json data is a string
      if (data['dsS3BucketThumbs'] && !(typeof data['dsS3BucketThumbs'] === 'string' || data['dsS3BucketThumbs'] instanceof String)) {
        throw new Error("Expected the field `dsS3BucketThumbs` to be a primitive type in the JSON string but got " + data['dsS3BucketThumbs']);
      }
      // ensure the json data is a string
      if (data['dsS3BucketVersions'] && !(typeof data['dsS3BucketVersions'] === 'string' || data['dsS3BucketVersions'] instanceof String)) {
        throw new Error("Expected the field `dsS3BucketVersions` to be a primitive type in the JSON string but got " + data['dsS3BucketVersions']);
      }
      // ensure the json data is a string
      if (data['dsS3Custom'] && !(typeof data['dsS3Custom'] === 'string' || data['dsS3Custom'] instanceof String)) {
        throw new Error("Expected the field `dsS3Custom` to be a primitive type in the JSON string but got " + data['dsS3Custom']);
      }
      // ensure the json data is a string
      if (data['dsS3CustomRegion'] && !(typeof data['dsS3CustomRegion'] === 'string' || data['dsS3CustomRegion'] instanceof String)) {
        throw new Error("Expected the field `dsS3CustomRegion` to be a primitive type in the JSON string but got " + data['dsS3CustomRegion']);
      }
      // ensure the json data is a string
      if (data['dsType'] && !(typeof data['dsType'] === 'string' || data['dsType'] instanceof String)) {
        throw new Error("Expected the field `dsType` to be a primitive type in the JSON string but got " + data['dsType']);
      }
      // ensure the json data is a string
      if (data['frontendApplicationTitle'] && !(typeof data['frontendApplicationTitle'] === 'string' || data['frontendApplicationTitle'] instanceof String)) {
        throw new Error("Expected the field `frontendApplicationTitle` to be a primitive type in the JSON string but got " + data['frontendApplicationTitle']);
      }
      // ensure the json data is a string
      if (data['frontendDefaultLanguage'] && !(typeof data['frontendDefaultLanguage'] === 'string' || data['frontendDefaultLanguage'] instanceof String)) {
        throw new Error("Expected the field `frontendDefaultLanguage` to be a primitive type in the JSON string but got " + data['frontendDefaultLanguage']);
      }
      // ensure the json data is a string
      if (data['frontendHosts'] && !(typeof data['frontendHosts'] === 'string' || data['frontendHosts'] instanceof String)) {
        throw new Error("Expected the field `frontendHosts` to be a primitive type in the JSON string but got " + data['frontendHosts']);
      }
      // ensure the json data is a string
      if (data['frontendLogin'] && !(typeof data['frontendLogin'] === 'string' || data['frontendLogin'] instanceof String)) {
        throw new Error("Expected the field `frontendLogin` to be a primitive type in the JSON string but got " + data['frontendLogin']);
      }
      // ensure the json data is a string
      if (data['frontendPassword'] && !(typeof data['frontendPassword'] === 'string' || data['frontendPassword'] instanceof String)) {
        throw new Error("Expected the field `frontendPassword` to be a primitive type in the JSON string but got " + data['frontendPassword']);
      }
      // ensure the json data is a string
      if (data['frontendRepeatPassword'] && !(typeof data['frontendRepeatPassword'] === 'string' || data['frontendRepeatPassword'] instanceof String)) {
        throw new Error("Expected the field `frontendRepeatPassword` to be a primitive type in the JSON string but got " + data['frontendRepeatPassword']);
      }
      // ensure the json data is a string
      if (data['internalUrl'] && !(typeof data['internalUrl'] === 'string' || data['internalUrl'] instanceof String)) {
        throw new Error("Expected the field `internalUrl` to be a primitive type in the JSON string but got " + data['internalUrl']);
      }
      // ensure the json data is a string
      if (data['licenseString'] && !(typeof data['licenseString'] === 'string' || data['licenseString'] instanceof String)) {
        throw new Error("Expected the field `licenseString` to be a primitive type in the JSON string but got " + data['licenseString']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {Array.<module:model/InstallCheckResult>} CheckResults
 */
InstallInstallConfig.prototype['CheckResults'] = undefined;

/**
 * @member {Object.<String, String>} CustomConfigs
 */
InstallInstallConfig.prototype['CustomConfigs'] = undefined;

/**
 * @member {String} DocumentsDSN
 */
InstallInstallConfig.prototype['DocumentsDSN'] = undefined;

/**
 * @member {module:model/InstallProxyConfig} ProxyConfig
 */
InstallInstallConfig.prototype['ProxyConfig'] = undefined;

/**
 * @member {Boolean} UseDocumentsDSN
 */
InstallInstallConfig.prototype['UseDocumentsDSN'] = undefined;

/**
 * @member {String} dbConnectionType
 */
InstallInstallConfig.prototype['dbConnectionType'] = undefined;

/**
 * @member {String} dbManualDSN
 */
InstallInstallConfig.prototype['dbManualDSN'] = undefined;

/**
 * @member {String} dbSocketFile
 */
InstallInstallConfig.prototype['dbSocketFile'] = undefined;

/**
 * @member {String} dbSocketName
 */
InstallInstallConfig.prototype['dbSocketName'] = undefined;

/**
 * @member {String} dbSocketPassword
 */
InstallInstallConfig.prototype['dbSocketPassword'] = undefined;

/**
 * @member {String} dbSocketUser
 */
InstallInstallConfig.prototype['dbSocketUser'] = undefined;

/**
 * @member {String} dbTCPHostname
 */
InstallInstallConfig.prototype['dbTCPHostname'] = undefined;

/**
 * @member {String} dbTCPName
 */
InstallInstallConfig.prototype['dbTCPName'] = undefined;

/**
 * @member {String} dbTCPPassword
 */
InstallInstallConfig.prototype['dbTCPPassword'] = undefined;

/**
 * @member {String} dbTCPPort
 */
InstallInstallConfig.prototype['dbTCPPort'] = undefined;

/**
 * @member {String} dbTCPUser
 */
InstallInstallConfig.prototype['dbTCPUser'] = undefined;

/**
 * @member {Boolean} dbUseDefaults
 */
InstallInstallConfig.prototype['dbUseDefaults'] = undefined;

/**
 * @member {String} dsFolder
 */
InstallInstallConfig.prototype['dsFolder'] = undefined;

/**
 * @member {String} dsName
 */
InstallInstallConfig.prototype['dsName'] = undefined;

/**
 * @member {String} dsPort
 */
InstallInstallConfig.prototype['dsPort'] = undefined;

/**
 * @member {String} dsS3ApiKey
 */
InstallInstallConfig.prototype['dsS3ApiKey'] = undefined;

/**
 * @member {String} dsS3ApiSecret
 */
InstallInstallConfig.prototype['dsS3ApiSecret'] = undefined;

/**
 * @member {String} dsS3BucketBinaries
 */
InstallInstallConfig.prototype['dsS3BucketBinaries'] = undefined;

/**
 * @member {String} dsS3BucketCells
 */
InstallInstallConfig.prototype['dsS3BucketCells'] = undefined;

/**
 * @member {String} dsS3BucketDefault
 */
InstallInstallConfig.prototype['dsS3BucketDefault'] = undefined;

/**
 * @member {String} dsS3BucketPersonal
 */
InstallInstallConfig.prototype['dsS3BucketPersonal'] = undefined;

/**
 * @member {String} dsS3BucketThumbs
 */
InstallInstallConfig.prototype['dsS3BucketThumbs'] = undefined;

/**
 * @member {String} dsS3BucketVersions
 */
InstallInstallConfig.prototype['dsS3BucketVersions'] = undefined;

/**
 * @member {String} dsS3Custom
 */
InstallInstallConfig.prototype['dsS3Custom'] = undefined;

/**
 * @member {String} dsS3CustomRegion
 */
InstallInstallConfig.prototype['dsS3CustomRegion'] = undefined;

/**
 * @member {String} dsType
 */
InstallInstallConfig.prototype['dsType'] = undefined;

/**
 * @member {String} frontendApplicationTitle
 */
InstallInstallConfig.prototype['frontendApplicationTitle'] = undefined;

/**
 * @member {String} frontendDefaultLanguage
 */
InstallInstallConfig.prototype['frontendDefaultLanguage'] = undefined;

/**
 * @member {String} frontendHosts
 */
InstallInstallConfig.prototype['frontendHosts'] = undefined;

/**
 * @member {String} frontendLogin
 */
InstallInstallConfig.prototype['frontendLogin'] = undefined;

/**
 * @member {String} frontendPassword
 */
InstallInstallConfig.prototype['frontendPassword'] = undefined;

/**
 * @member {String} frontendRepeatPassword
 */
InstallInstallConfig.prototype['frontendRepeatPassword'] = undefined;

/**
 * @member {String} internalUrl
 */
InstallInstallConfig.prototype['internalUrl'] = undefined;

/**
 * @member {Boolean} licenseRequired
 */
InstallInstallConfig.prototype['licenseRequired'] = undefined;

/**
 * @member {String} licenseString
 */
InstallInstallConfig.prototype['licenseString'] = undefined;
var _default = exports["default"] = InstallInstallConfig;
//# sourceMappingURL=InstallInstallConfig.js.map
