"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _defineProperty(e, r, t) { return (r = _toPropertyKey(r)) in e ? Object.defineProperty(e, r, { value: t, enumerable: !0, configurable: !0, writable: !0 }) : e[r] = t, e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
* Enum class InstallHeaderModAction.
* @enum {}
* @readonly
*/
var InstallHeaderModAction = exports["default"] = /*#__PURE__*/function () {
  function InstallHeaderModAction() {
    _classCallCheck(this, InstallHeaderModAction);
    /**
     * value: "APPEND_IF_EXISTS_OR_ADD"
     * @const
     */
    _defineProperty(this, "APPEND_IF_EXISTS_OR_ADD", "APPEND_IF_EXISTS_OR_ADD");
    /**
     * value: "ADD_IF_ABSENT"
     * @const
     */
    _defineProperty(this, "ADD_IF_ABSENT", "ADD_IF_ABSENT");
    /**
     * value: "OVERWRITE_IF_EXISTS_OR_ADD"
     * @const
     */
    _defineProperty(this, "OVERWRITE_IF_EXISTS_OR_ADD", "OVERWRITE_IF_EXISTS_OR_ADD");
    /**
     * value: "OVERWRITE_IF_EXISTS"
     * @const
     */
    _defineProperty(this, "OVERWRITE_IF_EXISTS", "OVERWRITE_IF_EXISTS");
    /**
     * value: "REMOVE"
     * @const
     */
    _defineProperty(this, "REMOVE", "REMOVE");
  }
  return _createClass(InstallHeaderModAction, null, [{
    key: "constructFromObject",
    value:
    /**
    * Returns a <code>InstallHeaderModAction</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/InstallHeaderModAction} The enum <code>InstallHeaderModAction</code> value.
    */
    function constructFromObject(object) {
      return object;
    }
  }]);
}();
//# sourceMappingURL=InstallHeaderModAction.js.map
