"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _JobsSelectorRange = _interopRequireDefault(require("./JobsSelectorRange"));
var _ServiceQuery = _interopRequireDefault(require("./ServiceQuery"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The JobsNodesSelector model module.
 * @module model/JobsNodesSelector
 * @version 4.0
 */
var JobsNodesSelector = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>JobsNodesSelector</code>.
   * @alias module:model/JobsNodesSelector
   */
  function JobsNodesSelector() {
    _classCallCheck(this, JobsNodesSelector);
    JobsNodesSelector.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(JobsNodesSelector, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>JobsNodesSelector</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobsNodesSelector} obj Optional instance to populate.
     * @return {module:model/JobsNodesSelector} The populated <code>JobsNodesSelector</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new JobsNodesSelector();
        if (data.hasOwnProperty('All')) {
          obj['All'] = _ApiClient["default"].convertToType(data['All'], 'Boolean');
        }
        if (data.hasOwnProperty('ClearInput')) {
          obj['ClearInput'] = _ApiClient["default"].convertToType(data['ClearInput'], 'Boolean');
        }
        if (data.hasOwnProperty('Collect')) {
          obj['Collect'] = _ApiClient["default"].convertToType(data['Collect'], 'Boolean');
        }
        if (data.hasOwnProperty('Description')) {
          obj['Description'] = _ApiClient["default"].convertToType(data['Description'], 'String');
        }
        if (data.hasOwnProperty('FanOutInput')) {
          obj['FanOutInput'] = _ApiClient["default"].convertToType(data['FanOutInput'], 'Boolean');
        }
        if (data.hasOwnProperty('Label')) {
          obj['Label'] = _ApiClient["default"].convertToType(data['Label'], 'String');
        }
        if (data.hasOwnProperty('Pathes')) {
          obj['Pathes'] = _ApiClient["default"].convertToType(data['Pathes'], ['String']);
        }
        if (data.hasOwnProperty('Query')) {
          obj['Query'] = _ServiceQuery["default"].constructFromObject(data['Query']);
        }
        if (data.hasOwnProperty('Range')) {
          obj['Range'] = _JobsSelectorRange["default"].constructFromObject(data['Range']);
        }
        if (data.hasOwnProperty('Timeout')) {
          obj['Timeout'] = _ApiClient["default"].convertToType(data['Timeout'], 'String');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobsNodesSelector</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobsNodesSelector</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is a string
      if (data['Description'] && !(typeof data['Description'] === 'string' || data['Description'] instanceof String)) {
        throw new Error("Expected the field `Description` to be a primitive type in the JSON string but got " + data['Description']);
      }
      // ensure the json data is a string
      if (data['Label'] && !(typeof data['Label'] === 'string' || data['Label'] instanceof String)) {
        throw new Error("Expected the field `Label` to be a primitive type in the JSON string but got " + data['Label']);
      }
      // ensure the json data is an array
      if (!Array.isArray(data['Pathes'])) {
        throw new Error("Expected the field `Pathes` to be an array in the JSON data but got " + data['Pathes']);
      }
      // validate the optional field `Query`
      if (data['Query']) {
        // data not null
        _ServiceQuery["default"].validateJSON(data['Query']);
      }
      // validate the optional field `Range`
      if (data['Range']) {
        // data not null
        _JobsSelectorRange["default"].validateJSON(data['Range']);
      }
      // ensure the json data is a string
      if (data['Timeout'] && !(typeof data['Timeout'] === 'string' || data['Timeout'] instanceof String)) {
        throw new Error("Expected the field `Timeout` to be a primitive type in the JSON string but got " + data['Timeout']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {Boolean} All
 */
JobsNodesSelector.prototype['All'] = undefined;

/**
 * @member {Boolean} ClearInput
 */
JobsNodesSelector.prototype['ClearInput'] = undefined;

/**
 * @member {Boolean} Collect
 */
JobsNodesSelector.prototype['Collect'] = undefined;

/**
 * @member {String} Description
 */
JobsNodesSelector.prototype['Description'] = undefined;

/**
 * @member {Boolean} FanOutInput
 */
JobsNodesSelector.prototype['FanOutInput'] = undefined;

/**
 * @member {String} Label
 */
JobsNodesSelector.prototype['Label'] = undefined;

/**
 * @member {Array.<String>} Pathes
 */
JobsNodesSelector.prototype['Pathes'] = undefined;

/**
 * @member {module:model/ServiceQuery} Query
 */
JobsNodesSelector.prototype['Query'] = undefined;

/**
 * @member {module:model/JobsSelectorRange} Range
 */
JobsNodesSelector.prototype['Range'] = undefined;

/**
 * @member {String} Timeout
 */
JobsNodesSelector.prototype['Timeout'] = undefined;
var _default = exports["default"] = JobsNodesSelector;
//# sourceMappingURL=JobsNodesSelector.js.map
