"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _JobsTaskStatus = _interopRequireDefault(require("./JobsTaskStatus"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The JobsListJobsRequest model module.
 * @module model/JobsListJobsRequest
 * @version 4.0
 */
var JobsListJobsRequest = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>JobsListJobsRequest</code>.
   * @alias module:model/JobsListJobsRequest
   */
  function JobsListJobsRequest() {
    _classCallCheck(this, JobsListJobsRequest);
    JobsListJobsRequest.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(JobsListJobsRequest, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>JobsListJobsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobsListJobsRequest} obj Optional instance to populate.
     * @return {module:model/JobsListJobsRequest} The populated <code>JobsListJobsRequest</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new JobsListJobsRequest();
        if (data.hasOwnProperty('EventsOnly')) {
          obj['EventsOnly'] = _ApiClient["default"].convertToType(data['EventsOnly'], 'Boolean');
        }
        if (data.hasOwnProperty('JobIDs')) {
          obj['JobIDs'] = _ApiClient["default"].convertToType(data['JobIDs'], ['String']);
        }
        if (data.hasOwnProperty('LoadTasks')) {
          obj['LoadTasks'] = _JobsTaskStatus["default"].constructFromObject(data['LoadTasks']);
        }
        if (data.hasOwnProperty('Owner')) {
          obj['Owner'] = _ApiClient["default"].convertToType(data['Owner'], 'String');
        }
        if (data.hasOwnProperty('TasksLimit')) {
          obj['TasksLimit'] = _ApiClient["default"].convertToType(data['TasksLimit'], 'Number');
        }
        if (data.hasOwnProperty('TasksOffset')) {
          obj['TasksOffset'] = _ApiClient["default"].convertToType(data['TasksOffset'], 'Number');
        }
        if (data.hasOwnProperty('TimersOnly')) {
          obj['TimersOnly'] = _ApiClient["default"].convertToType(data['TimersOnly'], 'Boolean');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobsListJobsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobsListJobsRequest</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is an array
      if (!Array.isArray(data['JobIDs'])) {
        throw new Error("Expected the field `JobIDs` to be an array in the JSON data but got " + data['JobIDs']);
      }
      // ensure the json data is a string
      if (data['Owner'] && !(typeof data['Owner'] === 'string' || data['Owner'] instanceof String)) {
        throw new Error("Expected the field `Owner` to be a primitive type in the JSON string but got " + data['Owner']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {Boolean} EventsOnly
 */
JobsListJobsRequest.prototype['EventsOnly'] = undefined;

/**
 * @member {Array.<String>} JobIDs
 */
JobsListJobsRequest.prototype['JobIDs'] = undefined;

/**
 * @member {module:model/JobsTaskStatus} LoadTasks
 */
JobsListJobsRequest.prototype['LoadTasks'] = undefined;

/**
 * @member {String} Owner
 */
JobsListJobsRequest.prototype['Owner'] = undefined;

/**
 * @member {Number} TasksLimit
 */
JobsListJobsRequest.prototype['TasksLimit'] = undefined;

/**
 * @member {Number} TasksOffset
 */
JobsListJobsRequest.prototype['TasksOffset'] = undefined;

/**
 * @member {Boolean} TimersOnly
 */
JobsListJobsRequest.prototype['TimersOnly'] = undefined;
var _default = exports["default"] = JobsListJobsRequest;
//# sourceMappingURL=JobsListJobsRequest.js.map
