"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _JobsActionLog = _interopRequireDefault(require("./JobsActionLog"));
var _JobsTaskStatus = _interopRequireDefault(require("./JobsTaskStatus"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The JobsTask model module.
 * @module model/JobsTask
 * @version 4.0
 */
var JobsTask = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>JobsTask</code>.
   * @alias module:model/JobsTask
   */
  function JobsTask() {
    _classCallCheck(this, JobsTask);
    JobsTask.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(JobsTask, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>JobsTask</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobsTask} obj Optional instance to populate.
     * @return {module:model/JobsTask} The populated <code>JobsTask</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new JobsTask();
        if (data.hasOwnProperty('ActionsLogs')) {
          obj['ActionsLogs'] = _ApiClient["default"].convertToType(data['ActionsLogs'], [_JobsActionLog["default"]]);
        }
        if (data.hasOwnProperty('CanPause')) {
          obj['CanPause'] = _ApiClient["default"].convertToType(data['CanPause'], 'Boolean');
        }
        if (data.hasOwnProperty('CanStop')) {
          obj['CanStop'] = _ApiClient["default"].convertToType(data['CanStop'], 'Boolean');
        }
        if (data.hasOwnProperty('EndTime')) {
          obj['EndTime'] = _ApiClient["default"].convertToType(data['EndTime'], 'Number');
        }
        if (data.hasOwnProperty('HasProgress')) {
          obj['HasProgress'] = _ApiClient["default"].convertToType(data['HasProgress'], 'Boolean');
        }
        if (data.hasOwnProperty('ID')) {
          obj['ID'] = _ApiClient["default"].convertToType(data['ID'], 'String');
        }
        if (data.hasOwnProperty('JobID')) {
          obj['JobID'] = _ApiClient["default"].convertToType(data['JobID'], 'String');
        }
        if (data.hasOwnProperty('Progress')) {
          obj['Progress'] = _ApiClient["default"].convertToType(data['Progress'], 'Number');
        }
        if (data.hasOwnProperty('StartTime')) {
          obj['StartTime'] = _ApiClient["default"].convertToType(data['StartTime'], 'Number');
        }
        if (data.hasOwnProperty('Status')) {
          obj['Status'] = _JobsTaskStatus["default"].constructFromObject(data['Status']);
        }
        if (data.hasOwnProperty('StatusMessage')) {
          obj['StatusMessage'] = _ApiClient["default"].convertToType(data['StatusMessage'], 'String');
        }
        if (data.hasOwnProperty('TriggerOwner')) {
          obj['TriggerOwner'] = _ApiClient["default"].convertToType(data['TriggerOwner'], 'String');
        }
      }
      return obj;
    }
  }]);
}();
/**
 * @member {Array.<module:model/JobsActionLog>} ActionsLogs
 */
JobsTask.prototype['ActionsLogs'] = undefined;

/**
 * @member {Boolean} CanPause
 */
JobsTask.prototype['CanPause'] = undefined;

/**
 * @member {Boolean} CanStop
 */
JobsTask.prototype['CanStop'] = undefined;

/**
 * @member {Number} EndTime
 */
JobsTask.prototype['EndTime'] = undefined;

/**
 * @member {Boolean} HasProgress
 */
JobsTask.prototype['HasProgress'] = undefined;

/**
 * @member {String} ID
 */
JobsTask.prototype['ID'] = undefined;

/**
 * @member {String} JobID
 */
JobsTask.prototype['JobID'] = undefined;

/**
 * @member {Number} Progress
 */
JobsTask.prototype['Progress'] = undefined;

/**
 * @member {Number} StartTime
 */
JobsTask.prototype['StartTime'] = undefined;

/**
 * @member {module:model/JobsTaskStatus} Status
 */
JobsTask.prototype['Status'] = undefined;

/**
 * @member {String} StatusMessage
 */
JobsTask.prototype['StatusMessage'] = undefined;

/**
 * @member {String} TriggerOwner
 */
JobsTask.prototype['TriggerOwner'] = undefined;
var _default = exports["default"] = JobsTask;
//# sourceMappingURL=JobsTask.js.map
