"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _JobsCommand = _interopRequireDefault(require("./JobsCommand"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The JobsCtrlCommand model module.
 * @module model/JobsCtrlCommand
 * @version 4.0
 */
var JobsCtrlCommand = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>JobsCtrlCommand</code>.
   * @alias module:model/JobsCtrlCommand
   */
  function JobsCtrlCommand() {
    _classCallCheck(this, JobsCtrlCommand);
    JobsCtrlCommand.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(JobsCtrlCommand, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>JobsCtrlCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobsCtrlCommand} obj Optional instance to populate.
     * @return {module:model/JobsCtrlCommand} The populated <code>JobsCtrlCommand</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new JobsCtrlCommand();
        if (data.hasOwnProperty('Cmd')) {
          obj['Cmd'] = _JobsCommand["default"].constructFromObject(data['Cmd']);
        }
        if (data.hasOwnProperty('JobId')) {
          obj['JobId'] = _ApiClient["default"].convertToType(data['JobId'], 'String');
        }
        if (data.hasOwnProperty('OwnerId')) {
          obj['OwnerId'] = _ApiClient["default"].convertToType(data['OwnerId'], 'String');
        }
        if (data.hasOwnProperty('RunParameters')) {
          obj['RunParameters'] = _ApiClient["default"].convertToType(data['RunParameters'], {
            'String': 'String'
          });
        }
        if (data.hasOwnProperty('TaskId')) {
          obj['TaskId'] = _ApiClient["default"].convertToType(data['TaskId'], 'String');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobsCtrlCommand</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobsCtrlCommand</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is a string
      if (data['JobId'] && !(typeof data['JobId'] === 'string' || data['JobId'] instanceof String)) {
        throw new Error("Expected the field `JobId` to be a primitive type in the JSON string but got " + data['JobId']);
      }
      // ensure the json data is a string
      if (data['OwnerId'] && !(typeof data['OwnerId'] === 'string' || data['OwnerId'] instanceof String)) {
        throw new Error("Expected the field `OwnerId` to be a primitive type in the JSON string but got " + data['OwnerId']);
      }
      // ensure the json data is a string
      if (data['TaskId'] && !(typeof data['TaskId'] === 'string' || data['TaskId'] instanceof String)) {
        throw new Error("Expected the field `TaskId` to be a primitive type in the JSON string but got " + data['TaskId']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {module:model/JobsCommand} Cmd
 */
JobsCtrlCommand.prototype['Cmd'] = undefined;

/**
 * @member {String} JobId
 */
JobsCtrlCommand.prototype['JobId'] = undefined;

/**
 * @member {String} OwnerId
 */
JobsCtrlCommand.prototype['OwnerId'] = undefined;

/**
 * @member {Object.<String, String>} RunParameters
 */
JobsCtrlCommand.prototype['RunParameters'] = undefined;

/**
 * @member {String} TaskId
 */
JobsCtrlCommand.prototype['TaskId'] = undefined;
var _default = exports["default"] = JobsCtrlCommand;
//# sourceMappingURL=JobsCtrlCommand.js.map
