"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _MailerUser = _interopRequireDefault(require("./MailerUser"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _createForOfIteratorHelper(r, e) { var t = "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (!t) { if (Array.isArray(r) || (t = _unsupportedIterableToArray(r)) || e && r && "number" == typeof r.length) { t && (r = t); var _n = 0, F = function F() {}; return { s: F, n: function n() { return _n >= r.length ? { done: !0 } : { done: !1, value: r[_n++] }; }, e: function e(r) { throw r; }, f: F }; } throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); } var o, a = !0, u = !1; return { s: function s() { t = t.call(r); }, n: function n() { var r = t.next(); return a = r.done, r; }, e: function e(r) { u = !0, o = r; }, f: function f() { try { a || null == t["return"] || t["return"](); } finally { if (u) throw o; } } }; }
function _unsupportedIterableToArray(r, a) { if (r) { if ("string" == typeof r) return _arrayLikeToArray(r, a); var t = {}.toString.call(r).slice(8, -1); return "Object" === t && r.constructor && (t = r.constructor.name), "Map" === t || "Set" === t ? Array.from(r) : "Arguments" === t || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t) ? _arrayLikeToArray(r, a) : void 0; } }
function _arrayLikeToArray(r, a) { (null == a || a > r.length) && (a = r.length); for (var e = 0, n = Array(a); e < a; e++) n[e] = r[e]; return n; }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The MailerMail model module.
 * @module model/MailerMail
 * @version 4.0
 */
var MailerMail = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>MailerMail</code>.
   * @alias module:model/MailerMail
   */
  function MailerMail() {
    _classCallCheck(this, MailerMail);
    MailerMail.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(MailerMail, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>MailerMail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MailerMail} obj Optional instance to populate.
     * @return {module:model/MailerMail} The populated <code>MailerMail</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new MailerMail();
        if (data.hasOwnProperty('Attachments')) {
          obj['Attachments'] = _ApiClient["default"].convertToType(data['Attachments'], ['String']);
        }
        if (data.hasOwnProperty('Cc')) {
          obj['Cc'] = _ApiClient["default"].convertToType(data['Cc'], [_MailerUser["default"]]);
        }
        if (data.hasOwnProperty('ContentHtml')) {
          obj['ContentHtml'] = _ApiClient["default"].convertToType(data['ContentHtml'], 'String');
        }
        if (data.hasOwnProperty('ContentMarkdown')) {
          obj['ContentMarkdown'] = _ApiClient["default"].convertToType(data['ContentMarkdown'], 'String');
        }
        if (data.hasOwnProperty('ContentPlain')) {
          obj['ContentPlain'] = _ApiClient["default"].convertToType(data['ContentPlain'], 'String');
        }
        if (data.hasOwnProperty('DateSent')) {
          obj['DateSent'] = _ApiClient["default"].convertToType(data['DateSent'], 'String');
        }
        if (data.hasOwnProperty('From')) {
          obj['From'] = _MailerUser["default"].constructFromObject(data['From']);
        }
        if (data.hasOwnProperty('Retries')) {
          obj['Retries'] = _ApiClient["default"].convertToType(data['Retries'], 'Number');
        }
        if (data.hasOwnProperty('Sender')) {
          obj['Sender'] = _MailerUser["default"].constructFromObject(data['Sender']);
        }
        if (data.hasOwnProperty('Subject')) {
          obj['Subject'] = _ApiClient["default"].convertToType(data['Subject'], 'String');
        }
        if (data.hasOwnProperty('TemplateData')) {
          obj['TemplateData'] = _ApiClient["default"].convertToType(data['TemplateData'], {
            'String': 'String'
          });
        }
        if (data.hasOwnProperty('TemplateId')) {
          obj['TemplateId'] = _ApiClient["default"].convertToType(data['TemplateId'], 'String');
        }
        if (data.hasOwnProperty('ThreadIndex')) {
          obj['ThreadIndex'] = _ApiClient["default"].convertToType(data['ThreadIndex'], 'String');
        }
        if (data.hasOwnProperty('ThreadUuid')) {
          obj['ThreadUuid'] = _ApiClient["default"].convertToType(data['ThreadUuid'], 'String');
        }
        if (data.hasOwnProperty('To')) {
          obj['To'] = _ApiClient["default"].convertToType(data['To'], [_MailerUser["default"]]);
        }
        if (data.hasOwnProperty('sendErrors')) {
          obj['sendErrors'] = _ApiClient["default"].convertToType(data['sendErrors'], ['String']);
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MailerMail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MailerMail</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is an array
      if (!Array.isArray(data['Attachments'])) {
        throw new Error("Expected the field `Attachments` to be an array in the JSON data but got " + data['Attachments']);
      }
      if (data['Cc']) {
        // data not null
        // ensure the json data is an array
        if (!Array.isArray(data['Cc'])) {
          throw new Error("Expected the field `Cc` to be an array in the JSON data but got " + data['Cc']);
        }
        // validate the optional field `Cc` (array)
        var _iterator = _createForOfIteratorHelper(data['Cc']),
          _step;
        try {
          for (_iterator.s(); !(_step = _iterator.n()).done;) {
            var item = _step.value;
            _MailerUser["default"].validateJSON(item);
          }
        } catch (err) {
          _iterator.e(err);
        } finally {
          _iterator.f();
        }
        ;
      }
      // ensure the json data is a string
      if (data['ContentHtml'] && !(typeof data['ContentHtml'] === 'string' || data['ContentHtml'] instanceof String)) {
        throw new Error("Expected the field `ContentHtml` to be a primitive type in the JSON string but got " + data['ContentHtml']);
      }
      // ensure the json data is a string
      if (data['ContentMarkdown'] && !(typeof data['ContentMarkdown'] === 'string' || data['ContentMarkdown'] instanceof String)) {
        throw new Error("Expected the field `ContentMarkdown` to be a primitive type in the JSON string but got " + data['ContentMarkdown']);
      }
      // ensure the json data is a string
      if (data['ContentPlain'] && !(typeof data['ContentPlain'] === 'string' || data['ContentPlain'] instanceof String)) {
        throw new Error("Expected the field `ContentPlain` to be a primitive type in the JSON string but got " + data['ContentPlain']);
      }
      // ensure the json data is a string
      if (data['DateSent'] && !(typeof data['DateSent'] === 'string' || data['DateSent'] instanceof String)) {
        throw new Error("Expected the field `DateSent` to be a primitive type in the JSON string but got " + data['DateSent']);
      }
      // validate the optional field `From`
      if (data['From']) {
        // data not null
        _MailerUser["default"].validateJSON(data['From']);
      }
      // validate the optional field `Sender`
      if (data['Sender']) {
        // data not null
        _MailerUser["default"].validateJSON(data['Sender']);
      }
      // ensure the json data is a string
      if (data['Subject'] && !(typeof data['Subject'] === 'string' || data['Subject'] instanceof String)) {
        throw new Error("Expected the field `Subject` to be a primitive type in the JSON string but got " + data['Subject']);
      }
      // ensure the json data is a string
      if (data['TemplateId'] && !(typeof data['TemplateId'] === 'string' || data['TemplateId'] instanceof String)) {
        throw new Error("Expected the field `TemplateId` to be a primitive type in the JSON string but got " + data['TemplateId']);
      }
      // ensure the json data is a string
      if (data['ThreadIndex'] && !(typeof data['ThreadIndex'] === 'string' || data['ThreadIndex'] instanceof String)) {
        throw new Error("Expected the field `ThreadIndex` to be a primitive type in the JSON string but got " + data['ThreadIndex']);
      }
      // ensure the json data is a string
      if (data['ThreadUuid'] && !(typeof data['ThreadUuid'] === 'string' || data['ThreadUuid'] instanceof String)) {
        throw new Error("Expected the field `ThreadUuid` to be a primitive type in the JSON string but got " + data['ThreadUuid']);
      }
      if (data['To']) {
        // data not null
        // ensure the json data is an array
        if (!Array.isArray(data['To'])) {
          throw new Error("Expected the field `To` to be an array in the JSON data but got " + data['To']);
        }
        // validate the optional field `To` (array)
        var _iterator2 = _createForOfIteratorHelper(data['To']),
          _step2;
        try {
          for (_iterator2.s(); !(_step2 = _iterator2.n()).done;) {
            var _item = _step2.value;
            _MailerUser["default"].validateJSON(_item);
          }
        } catch (err) {
          _iterator2.e(err);
        } finally {
          _iterator2.f();
        }
        ;
      }
      // ensure the json data is an array
      if (!Array.isArray(data['sendErrors'])) {
        throw new Error("Expected the field `sendErrors` to be an array in the JSON data but got " + data['sendErrors']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {Array.<String>} Attachments
 */
MailerMail.prototype['Attachments'] = undefined;

/**
 * @member {Array.<module:model/MailerUser>} Cc
 */
MailerMail.prototype['Cc'] = undefined;

/**
 * @member {String} ContentHtml
 */
MailerMail.prototype['ContentHtml'] = undefined;

/**
 * @member {String} ContentMarkdown
 */
MailerMail.prototype['ContentMarkdown'] = undefined;

/**
 * @member {String} ContentPlain
 */
MailerMail.prototype['ContentPlain'] = undefined;

/**
 * @member {String} DateSent
 */
MailerMail.prototype['DateSent'] = undefined;

/**
 * @member {module:model/MailerUser} From
 */
MailerMail.prototype['From'] = undefined;

/**
 * @member {Number} Retries
 */
MailerMail.prototype['Retries'] = undefined;

/**
 * @member {module:model/MailerUser} Sender
 */
MailerMail.prototype['Sender'] = undefined;

/**
 * @member {String} Subject
 */
MailerMail.prototype['Subject'] = undefined;

/**
 * @member {Object.<String, String>} TemplateData
 */
MailerMail.prototype['TemplateData'] = undefined;

/**
 * @member {String} TemplateId
 */
MailerMail.prototype['TemplateId'] = undefined;

/**
 * @member {String} ThreadIndex
 */
MailerMail.prototype['ThreadIndex'] = undefined;

/**
 * @member {String} ThreadUuid
 */
MailerMail.prototype['ThreadUuid'] = undefined;

/**
 * @member {Array.<module:model/MailerUser>} To
 */
MailerMail.prototype['To'] = undefined;

/**
 * @member {Array.<String>} sendErrors
 */
MailerMail.prototype['sendErrors'] = undefined;
var _default = exports["default"] = MailerMail;
//# sourceMappingURL=MailerMail.js.map
