"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The RegistryNode model module.
 * @module model/RegistryNode
 * @version 4.0
 */
var RegistryNode = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>RegistryNode</code>.
   * @alias module:model/RegistryNode
   */
  function RegistryNode() {
    _classCallCheck(this, RegistryNode);
    RegistryNode.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(RegistryNode, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>RegistryNode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegistryNode} obj Optional instance to populate.
     * @return {module:model/RegistryNode} The populated <code>RegistryNode</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new RegistryNode();
        if (data.hasOwnProperty('advertiseIp')) {
          obj['advertiseIp'] = _ApiClient["default"].convertToType(data['advertiseIp'], 'String');
        }
        if (data.hasOwnProperty('hostname')) {
          obj['hostname'] = _ApiClient["default"].convertToType(data['hostname'], 'String');
        }
        if (data.hasOwnProperty('ips')) {
          obj['ips'] = _ApiClient["default"].convertToType(data['ips'], ['String']);
        }
        if (data.hasOwnProperty('machine')) {
          obj['machine'] = _ApiClient["default"].convertToType(data['machine'], 'String');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegistryNode</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegistryNode</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is a string
      if (data['advertiseIp'] && !(typeof data['advertiseIp'] === 'string' || data['advertiseIp'] instanceof String)) {
        throw new Error("Expected the field `advertiseIp` to be a primitive type in the JSON string but got " + data['advertiseIp']);
      }
      // ensure the json data is a string
      if (data['hostname'] && !(typeof data['hostname'] === 'string' || data['hostname'] instanceof String)) {
        throw new Error("Expected the field `hostname` to be a primitive type in the JSON string but got " + data['hostname']);
      }
      // ensure the json data is an array
      if (!Array.isArray(data['ips'])) {
        throw new Error("Expected the field `ips` to be an array in the JSON data but got " + data['ips']);
      }
      // ensure the json data is a string
      if (data['machine'] && !(typeof data['machine'] === 'string' || data['machine'] instanceof String)) {
        throw new Error("Expected the field `machine` to be a primitive type in the JSON string but got " + data['machine']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {String} advertiseIp
 */
RegistryNode.prototype['advertiseIp'] = undefined;

/**
 * @member {String} hostname
 */
RegistryNode.prototype['hostname'] = undefined;

/**
 * @member {Array.<String>} ips
 */
RegistryNode.prototype['ips'] = undefined;

/**
 * @member {String} machine
 */
RegistryNode.prototype['machine'] = undefined;
var _default = exports["default"] = RegistryNode;
//# sourceMappingURL=RegistryNode.js.map
