"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _RestSettingsEntryMeta = _interopRequireDefault(require("./RestSettingsEntryMeta"));
var _RestSettingsSection = _interopRequireDefault(require("./RestSettingsSection"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The RestSettingsMenuResponse model module.
 * @module model/RestSettingsMenuResponse
 * @version 4.0
 */
var RestSettingsMenuResponse = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>RestSettingsMenuResponse</code>.
   * @alias module:model/RestSettingsMenuResponse
   */
  function RestSettingsMenuResponse() {
    _classCallCheck(this, RestSettingsMenuResponse);
    RestSettingsMenuResponse.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(RestSettingsMenuResponse, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>RestSettingsMenuResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestSettingsMenuResponse} obj Optional instance to populate.
     * @return {module:model/RestSettingsMenuResponse} The populated <code>RestSettingsMenuResponse</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new RestSettingsMenuResponse();
        if (data.hasOwnProperty('Sections')) {
          obj['Sections'] = _ApiClient["default"].convertToType(data['Sections'], [_RestSettingsSection["default"]]);
        }
        if (data.hasOwnProperty('__metadata__')) {
          obj['__metadata__'] = _RestSettingsEntryMeta["default"].constructFromObject(data['__metadata__']);
        }
      }
      return obj;
    }
  }]);
}();
/**
 * @member {Array.<module:model/RestSettingsSection>} Sections
 */
RestSettingsMenuResponse.prototype['Sections'] = undefined;

/**
 * @member {module:model/RestSettingsEntryMeta} __metadata__
 */
RestSettingsMenuResponse.prototype['__metadata__'] = undefined;
var _default = exports["default"] = RestSettingsMenuResponse;
//# sourceMappingURL=RestSettingsMenuResponse.js.map
