"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _RestShareLink = _interopRequireDefault(require("./RestShareLink"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The RestPutShareLinkRequest model module.
 * @module model/RestPutShareLinkRequest
 * @version 4.0
 */
var RestPutShareLinkRequest = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>RestPutShareLinkRequest</code>.
   * @alias module:model/RestPutShareLinkRequest
   */
  function RestPutShareLinkRequest() {
    _classCallCheck(this, RestPutShareLinkRequest);
    RestPutShareLinkRequest.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(RestPutShareLinkRequest, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>RestPutShareLinkRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestPutShareLinkRequest} obj Optional instance to populate.
     * @return {module:model/RestPutShareLinkRequest} The populated <code>RestPutShareLinkRequest</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new RestPutShareLinkRequest();
        if (data.hasOwnProperty('CreatePassword')) {
          obj['CreatePassword'] = _ApiClient["default"].convertToType(data['CreatePassword'], 'String');
        }
        if (data.hasOwnProperty('PasswordEnabled')) {
          obj['PasswordEnabled'] = _ApiClient["default"].convertToType(data['PasswordEnabled'], 'Boolean');
        }
        if (data.hasOwnProperty('ShareLink')) {
          obj['ShareLink'] = _RestShareLink["default"].constructFromObject(data['ShareLink']);
        }
        if (data.hasOwnProperty('UpdateCustomHash')) {
          obj['UpdateCustomHash'] = _ApiClient["default"].convertToType(data['UpdateCustomHash'], 'String');
        }
        if (data.hasOwnProperty('UpdatePassword')) {
          obj['UpdatePassword'] = _ApiClient["default"].convertToType(data['UpdatePassword'], 'String');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestPutShareLinkRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestPutShareLinkRequest</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is a string
      if (data['CreatePassword'] && !(typeof data['CreatePassword'] === 'string' || data['CreatePassword'] instanceof String)) {
        throw new Error("Expected the field `CreatePassword` to be a primitive type in the JSON string but got " + data['CreatePassword']);
      }
      // validate the optional field `ShareLink`
      if (data['ShareLink']) {
        // data not null
        _RestShareLink["default"].validateJSON(data['ShareLink']);
      }
      // ensure the json data is a string
      if (data['UpdateCustomHash'] && !(typeof data['UpdateCustomHash'] === 'string' || data['UpdateCustomHash'] instanceof String)) {
        throw new Error("Expected the field `UpdateCustomHash` to be a primitive type in the JSON string but got " + data['UpdateCustomHash']);
      }
      // ensure the json data is a string
      if (data['UpdatePassword'] && !(typeof data['UpdatePassword'] === 'string' || data['UpdatePassword'] instanceof String)) {
        throw new Error("Expected the field `UpdatePassword` to be a primitive type in the JSON string but got " + data['UpdatePassword']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {String} CreatePassword
 */
RestPutShareLinkRequest.prototype['CreatePassword'] = undefined;

/**
 * @member {Boolean} PasswordEnabled
 */
RestPutShareLinkRequest.prototype['PasswordEnabled'] = undefined;

/**
 * @member {module:model/RestShareLink} ShareLink
 */
RestPutShareLinkRequest.prototype['ShareLink'] = undefined;

/**
 * @member {String} UpdateCustomHash
 */
RestPutShareLinkRequest.prototype['UpdateCustomHash'] = undefined;

/**
 * @member {String} UpdatePassword
 */
RestPutShareLinkRequest.prototype['UpdatePassword'] = undefined;
var _default = exports["default"] = RestPutShareLinkRequest;
//# sourceMappingURL=RestPutShareLinkRequest.js.map
