"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _RestSettingsAccess = _interopRequireDefault(require("./RestSettingsAccess"));
var _RestSettingsEntryMeta = _interopRequireDefault(require("./RestSettingsEntryMeta"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The RestSettingsEntry model module.
 * @module model/RestSettingsEntry
 * @version 4.0
 */
var RestSettingsEntry = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>RestSettingsEntry</code>.
   * @alias module:model/RestSettingsEntry
   */
  function RestSettingsEntry() {
    _classCallCheck(this, RestSettingsEntry);
    RestSettingsEntry.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(RestSettingsEntry, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>RestSettingsEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestSettingsEntry} obj Optional instance to populate.
     * @return {module:model/RestSettingsEntry} The populated <code>RestSettingsEntry</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new RestSettingsEntry();
        if (data.hasOwnProperty('ALIAS')) {
          obj['ALIAS'] = _ApiClient["default"].convertToType(data['ALIAS'], 'String');
        }
        if (data.hasOwnProperty('Accesses')) {
          obj['Accesses'] = _ApiClient["default"].convertToType(data['Accesses'], {
            'String': _RestSettingsAccess["default"]
          });
        }
        if (data.hasOwnProperty('DESCRIPTION')) {
          obj['DESCRIPTION'] = _ApiClient["default"].convertToType(data['DESCRIPTION'], 'String');
        }
        if (data.hasOwnProperty('Feature')) {
          obj['Feature'] = _ApiClient["default"].convertToType(data['Feature'], 'String');
        }
        if (data.hasOwnProperty('Key')) {
          obj['Key'] = _ApiClient["default"].convertToType(data['Key'], 'String');
        }
        if (data.hasOwnProperty('LABEL')) {
          obj['LABEL'] = _ApiClient["default"].convertToType(data['LABEL'], 'String');
        }
        if (data.hasOwnProperty('MANAGER')) {
          obj['MANAGER'] = _ApiClient["default"].convertToType(data['MANAGER'], 'String');
        }
        if (data.hasOwnProperty('METADATA')) {
          obj['METADATA'] = _RestSettingsEntryMeta["default"].constructFromObject(data['METADATA']);
        }
      }
      return obj;
    }
  }]);
}();
/**
 * @member {String} ALIAS
 */
RestSettingsEntry.prototype['ALIAS'] = undefined;

/**
 * @member {Object.<String, module:model/RestSettingsAccess>} Accesses
 */
RestSettingsEntry.prototype['Accesses'] = undefined;

/**
 * @member {String} DESCRIPTION
 */
RestSettingsEntry.prototype['DESCRIPTION'] = undefined;

/**
 * @member {String} Feature
 */
RestSettingsEntry.prototype['Feature'] = undefined;

/**
 * @member {String} Key
 */
RestSettingsEntry.prototype['Key'] = undefined;

/**
 * @member {String} LABEL
 */
RestSettingsEntry.prototype['LABEL'] = undefined;

/**
 * @member {String} MANAGER
 */
RestSettingsEntry.prototype['MANAGER'] = undefined;

/**
 * @member {module:model/RestSettingsEntryMeta} METADATA
 */
RestSettingsEntry.prototype['METADATA'] = undefined;
var _default = exports["default"] = RestSettingsEntry;
//# sourceMappingURL=RestSettingsEntry.js.map
