"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _ProtobufAny = _interopRequireDefault(require("./ProtobufAny"));
var _ServiceOperationType = _interopRequireDefault(require("./ServiceOperationType"));
var _ServiceResourcePolicyQuery = _interopRequireDefault(require("./ServiceResourcePolicyQuery"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The ServiceQuery model module.
 * @module model/ServiceQuery
 * @version 4.0
 */
var ServiceQuery = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>ServiceQuery</code>.
   * @alias module:model/ServiceQuery
   */
  function ServiceQuery() {
    _classCallCheck(this, ServiceQuery);
    ServiceQuery.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(ServiceQuery, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>ServiceQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceQuery} obj Optional instance to populate.
     * @return {module:model/ServiceQuery} The populated <code>ServiceQuery</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ServiceQuery();
        if (data.hasOwnProperty('Limit')) {
          obj['Limit'] = _ApiClient["default"].convertToType(data['Limit'], 'String');
        }
        if (data.hasOwnProperty('Offset')) {
          obj['Offset'] = _ApiClient["default"].convertToType(data['Offset'], 'String');
        }
        if (data.hasOwnProperty('Operation')) {
          obj['Operation'] = _ServiceOperationType["default"].constructFromObject(data['Operation']);
        }
        if (data.hasOwnProperty('ResourcePolicyQuery')) {
          obj['ResourcePolicyQuery'] = _ServiceResourcePolicyQuery["default"].constructFromObject(data['ResourcePolicyQuery']);
        }
        if (data.hasOwnProperty('SortDesc')) {
          obj['SortDesc'] = _ApiClient["default"].convertToType(data['SortDesc'], 'Boolean');
        }
        if (data.hasOwnProperty('SortField')) {
          obj['SortField'] = _ApiClient["default"].convertToType(data['SortField'], 'String');
        }
        if (data.hasOwnProperty('SubQueries')) {
          obj['SubQueries'] = _ApiClient["default"].convertToType(data['SubQueries'], [_ProtobufAny["default"]]);
        }
        if (data.hasOwnProperty('groupBy')) {
          obj['groupBy'] = _ApiClient["default"].convertToType(data['groupBy'], 'Number');
        }
      }
      return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceQuery</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceQuery</code>.
     */
  }, {
    key: "validateJSON",
    value: function validateJSON(data) {
      // ensure the json data is a string
      if (data['Limit'] && !(typeof data['Limit'] === 'string' || data['Limit'] instanceof String)) {
        throw new Error("Expected the field `Limit` to be a primitive type in the JSON string but got " + data['Limit']);
      }
      // ensure the json data is a string
      if (data['Offset'] && !(typeof data['Offset'] === 'string' || data['Offset'] instanceof String)) {
        throw new Error("Expected the field `Offset` to be a primitive type in the JSON string but got " + data['Offset']);
      }
      // validate the optional field `ResourcePolicyQuery`
      if (data['ResourcePolicyQuery']) {
        // data not null
        _ServiceResourcePolicyQuery["default"].validateJSON(data['ResourcePolicyQuery']);
      }
      // ensure the json data is a string
      if (data['SortField'] && !(typeof data['SortField'] === 'string' || data['SortField'] instanceof String)) {
        throw new Error("Expected the field `SortField` to be a primitive type in the JSON string but got " + data['SortField']);
      }
      // ensure the json data is an array
      if (!Array.isArray(data['SubQueries'])) {
        throw new Error("Expected the field `SubQueries` to be an array in the JSON data but got " + data['SubQueries']);
      }
      return true;
    }
  }]);
}();
/**
 * @member {String} Limit
 */
ServiceQuery.prototype['Limit'] = undefined;

/**
 * @member {String} Offset
 */
ServiceQuery.prototype['Offset'] = undefined;

/**
 * @member {module:model/ServiceOperationType} Operation
 */
ServiceQuery.prototype['Operation'] = undefined;

/**
 * @member {module:model/ServiceResourcePolicyQuery} ResourcePolicyQuery
 */
ServiceQuery.prototype['ResourcePolicyQuery'] = undefined;

/**
 * @member {Boolean} SortDesc
 */
ServiceQuery.prototype['SortDesc'] = undefined;

/**
 * @member {String} SortField
 */
ServiceQuery.prototype['SortField'] = undefined;

/**
 * @member {Array.<module:model/ProtobufAny>} SubQueries
 */
ServiceQuery.prototype['SubQueries'] = undefined;

/**
 * @member {Number} groupBy
 */
ServiceQuery.prototype['groupBy'] = undefined;
var _default = exports["default"] = ServiceQuery;
//# sourceMappingURL=ServiceQuery.js.map
