"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
var _ApiClient = _interopRequireDefault(require("../ApiClient"));
var _IdmRole = _interopRequireDefault(require("./IdmRole"));
var _ServiceResourcePolicy = _interopRequireDefault(require("./ServiceResourcePolicy"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { "default": e }; }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); } /**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The UserCanRepresentEitherAUserOrAGroup1 model module.
 * @module model/UserCanRepresentEitherAUserOrAGroup1
 * @version 4.0
 */
var UserCanRepresentEitherAUserOrAGroup1 = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>UserCanRepresentEitherAUserOrAGroup1</code>.
   * @alias module:model/UserCanRepresentEitherAUserOrAGroup1
   */
  function UserCanRepresentEitherAUserOrAGroup1() {
    _classCallCheck(this, UserCanRepresentEitherAUserOrAGroup1);
    UserCanRepresentEitherAUserOrAGroup1.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  return _createClass(UserCanRepresentEitherAUserOrAGroup1, null, [{
    key: "initialize",
    value: function initialize(obj) {}

    /**
     * Constructs a <code>UserCanRepresentEitherAUserOrAGroup1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCanRepresentEitherAUserOrAGroup1} obj Optional instance to populate.
     * @return {module:model/UserCanRepresentEitherAUserOrAGroup1} The populated <code>UserCanRepresentEitherAUserOrAGroup1</code> instance.
     */
  }, {
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new UserCanRepresentEitherAUserOrAGroup1();
        if (data.hasOwnProperty('Attributes')) {
          obj['Attributes'] = _ApiClient["default"].convertToType(data['Attributes'], {
            'String': 'String'
          });
        }
        if (data.hasOwnProperty('GroupLabel')) {
          obj['GroupLabel'] = _ApiClient["default"].convertToType(data['GroupLabel'], 'String');
        }
        if (data.hasOwnProperty('GroupPath')) {
          obj['GroupPath'] = _ApiClient["default"].convertToType(data['GroupPath'], 'String');
        }
        if (data.hasOwnProperty('IsGroup')) {
          obj['IsGroup'] = _ApiClient["default"].convertToType(data['IsGroup'], 'Boolean');
        }
        if (data.hasOwnProperty('LastConnected')) {
          obj['LastConnected'] = _ApiClient["default"].convertToType(data['LastConnected'], 'Number');
        }
        if (data.hasOwnProperty('OldPassword')) {
          obj['OldPassword'] = _ApiClient["default"].convertToType(data['OldPassword'], 'String');
        }
        if (data.hasOwnProperty('Password')) {
          obj['Password'] = _ApiClient["default"].convertToType(data['Password'], 'String');
        }
        if (data.hasOwnProperty('Policies')) {
          obj['Policies'] = _ApiClient["default"].convertToType(data['Policies'], [_ServiceResourcePolicy["default"]]);
        }
        if (data.hasOwnProperty('PoliciesContextEditable')) {
          obj['PoliciesContextEditable'] = _ApiClient["default"].convertToType(data['PoliciesContextEditable'], 'Boolean');
        }
        if (data.hasOwnProperty('Roles')) {
          obj['Roles'] = _ApiClient["default"].convertToType(data['Roles'], [_IdmRole["default"]]);
        }
        if (data.hasOwnProperty('Uuid')) {
          obj['Uuid'] = _ApiClient["default"].convertToType(data['Uuid'], 'String');
        }
      }
      return obj;
    }
  }]);
}();
/**
 * @member {Object.<String, String>} Attributes
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['Attributes'] = undefined;

/**
 * @member {String} GroupLabel
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['GroupLabel'] = undefined;

/**
 * @member {String} GroupPath
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['GroupPath'] = undefined;

/**
 * @member {Boolean} IsGroup
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['IsGroup'] = undefined;

/**
 * @member {Number} LastConnected
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['LastConnected'] = undefined;

/**
 * @member {String} OldPassword
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['OldPassword'] = undefined;

/**
 * @member {String} Password
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['Password'] = undefined;

/**
 * @member {Array.<module:model/ServiceResourcePolicy>} Policies
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['Policies'] = undefined;

/**
 * Context-resolved to quickly check if user is editable or not.
 * @member {Boolean} PoliciesContextEditable
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['PoliciesContextEditable'] = undefined;

/**
 * @member {Array.<module:model/IdmRole>} Roles
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['Roles'] = undefined;

/**
 * @member {String} Uuid
 */
UserCanRepresentEitherAUserOrAGroup1.prototype['Uuid'] = undefined;
var _default = exports["default"] = UserCanRepresentEitherAUserOrAGroup1;
//# sourceMappingURL=UserCanRepresentEitherAUserOrAGroup1.js.map
