/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import IdmListPolicyGroupsRequest from '../model/IdmListPolicyGroupsRequest';
import IdmListPolicyGroupsResponse from '../model/IdmListPolicyGroupsResponse';
import RestError from '../model/RestError';

/**
* PolicyService service.
* @module api/PolicyServiceApi
* @version 4.0
*/
export default class PolicyServiceApi {

    /**
    * Constructs a new PolicyServiceApi. 
    * @alias module:api/PolicyServiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * List all defined security policies
     * @param {module:model/IdmListPolicyGroupsRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/IdmListPolicyGroupsResponse} and HTTP response
     */
    listPoliciesWithHttpInfo(body) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling listPolicies");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = IdmListPolicyGroupsResponse;
      return this.apiClient.callApi(
        '/policy', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List all defined security policies
     * @param {module:model/IdmListPolicyGroupsRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/IdmListPolicyGroupsResponse}
     */
    listPolicies(body) {
      return this.listPoliciesWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
