/**
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import IdmUser from '../model/IdmUser';
import RestDeleteResponse from '../model/RestDeleteResponse';
import RestError from '../model/RestError';
import RestSearchUserRequest from '../model/RestSearchUserRequest';
import RestUsersCollection from '../model/RestUsersCollection';
import UserCanRepresentEitherAUserOrAGroup from '../model/UserCanRepresentEitherAUserOrAGroup';
import UserCanRepresentEitherAUserOrAGroup1 from '../model/UserCanRepresentEitherAUserOrAGroup1';

/**
* UserService service.
* @module api/UserServiceApi
* @version 4.0
*/
export default class UserServiceApi {

    /**
    * Constructs a new UserServiceApi. 
    * @alias module:api/UserServiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Delete a user
     * @param {String} Login User login is used to connect, field is empty for groups
     * @param {Object} opts Optional parameters
     * @param {String} opts.Uuid User unique identifier.
     * @param {String} opts.GroupPath Path to the parent group.
     * @param {String} opts.Password Password can be passed to be updated (but never read back), field is empty for groups.
     * @param {String} opts.OldPassword OldPassword must be set when a user updates her own password.
     * @param {Boolean} opts.IsGroup Whether this object is a group or a user.
     * @param {String} opts.GroupLabel Label of the group, field is empty for users.
     * @param {Number} opts.LastConnected Last successful connection timestamp.
     * @param {Boolean} opts.PoliciesContextEditable Context-resolved to quickly check if user is editable or not.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RestDeleteResponse} and HTTP response
     */
    deleteUserWithHttpInfo(Login, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'Login' is set
      if (Login === undefined || Login === null) {
        throw new Error("Missing the required parameter 'Login' when calling deleteUser");
      }

      let pathParams = {
        'Login': Login
      };
      let queryParams = {
        'Uuid': opts['Uuid'],
        'GroupPath': opts['GroupPath'],
        'Password': opts['Password'],
        'OldPassword': opts['OldPassword'],
        'IsGroup': opts['IsGroup'],
        'GroupLabel': opts['GroupLabel'],
        'LastConnected': opts['LastConnected'],
        'PoliciesContextEditable': opts['PoliciesContextEditable']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RestDeleteResponse;
      return this.apiClient.callApi(
        '/user/{Login}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a user
     * @param {String} Login User login is used to connect, field is empty for groups
     * @param {Object} opts Optional parameters
     * @param {String} opts.Uuid User unique identifier.
     * @param {String} opts.GroupPath Path to the parent group.
     * @param {String} opts.Password Password can be passed to be updated (but never read back), field is empty for groups.
     * @param {String} opts.OldPassword OldPassword must be set when a user updates her own password.
     * @param {Boolean} opts.IsGroup Whether this object is a group or a user.
     * @param {String} opts.GroupLabel Label of the group, field is empty for users.
     * @param {Number} opts.LastConnected Last successful connection timestamp.
     * @param {Boolean} opts.PoliciesContextEditable Context-resolved to quickly check if user is editable or not.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RestDeleteResponse}
     */
    deleteUser(Login, opts) {
      return this.deleteUserWithHttpInfo(Login, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a user by login
     * @param {String} Login User login is used to connect, field is empty for groups
     * @param {Object} opts Optional parameters
     * @param {String} opts.Uuid User unique identifier.
     * @param {String} opts.GroupPath Path to the parent group.
     * @param {String} opts.Password Password can be passed to be updated (but never read back), field is empty for groups.
     * @param {String} opts.OldPassword OldPassword must be set when a user updates her own password.
     * @param {Boolean} opts.IsGroup Whether this object is a group or a user.
     * @param {String} opts.GroupLabel Label of the group, field is empty for users.
     * @param {Number} opts.LastConnected Last successful connection timestamp.
     * @param {Boolean} opts.PoliciesContextEditable Context-resolved to quickly check if user is editable or not.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/IdmUser} and HTTP response
     */
    getUserWithHttpInfo(Login, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'Login' is set
      if (Login === undefined || Login === null) {
        throw new Error("Missing the required parameter 'Login' when calling getUser");
      }

      let pathParams = {
        'Login': Login
      };
      let queryParams = {
        'Uuid': opts['Uuid'],
        'GroupPath': opts['GroupPath'],
        'Password': opts['Password'],
        'OldPassword': opts['OldPassword'],
        'IsGroup': opts['IsGroup'],
        'GroupLabel': opts['GroupLabel'],
        'LastConnected': opts['LastConnected'],
        'PoliciesContextEditable': opts['PoliciesContextEditable']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = IdmUser;
      return this.apiClient.callApi(
        '/user/{Login}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a user by login
     * @param {String} Login User login is used to connect, field is empty for groups
     * @param {Object} opts Optional parameters
     * @param {String} opts.Uuid User unique identifier.
     * @param {String} opts.GroupPath Path to the parent group.
     * @param {String} opts.Password Password can be passed to be updated (but never read back), field is empty for groups.
     * @param {String} opts.OldPassword OldPassword must be set when a user updates her own password.
     * @param {Boolean} opts.IsGroup Whether this object is a group or a user.
     * @param {String} opts.GroupLabel Label of the group, field is empty for users.
     * @param {Number} opts.LastConnected Last successful connection timestamp.
     * @param {Boolean} opts.PoliciesContextEditable Context-resolved to quickly check if user is editable or not.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/IdmUser}
     */
    getUser(Login, opts) {
      return this.getUserWithHttpInfo(Login, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Just save a user roles, without other datas
     * @param {String} Login User login is used to connect, field is empty for groups
     * @param {module:model/UserCanRepresentEitherAUserOrAGroup} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/IdmUser} and HTTP response
     */
    putRolesWithHttpInfo(Login, body) {
      let postBody = body;
      // verify the required parameter 'Login' is set
      if (Login === undefined || Login === null) {
        throw new Error("Missing the required parameter 'Login' when calling putRoles");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putRoles");
      }

      let pathParams = {
        'Login': Login
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = IdmUser;
      return this.apiClient.callApi(
        '/user/roles/{Login}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Just save a user roles, without other datas
     * @param {String} Login User login is used to connect, field is empty for groups
     * @param {module:model/UserCanRepresentEitherAUserOrAGroup} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/IdmUser}
     */
    putRoles(Login, body) {
      return this.putRolesWithHttpInfo(Login, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create or update a user
     * @param {String} Login User login is used to connect, field is empty for groups
     * @param {module:model/UserCanRepresentEitherAUserOrAGroup1} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/IdmUser} and HTTP response
     */
    putUserWithHttpInfo(Login, body) {
      let postBody = body;
      // verify the required parameter 'Login' is set
      if (Login === undefined || Login === null) {
        throw new Error("Missing the required parameter 'Login' when calling putUser");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putUser");
      }

      let pathParams = {
        'Login': Login
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = IdmUser;
      return this.apiClient.callApi(
        '/user/{Login}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create or update a user
     * @param {String} Login User login is used to connect, field is empty for groups
     * @param {module:model/UserCanRepresentEitherAUserOrAGroup1} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/IdmUser}
     */
    putUser(Login, body) {
      return this.putUserWithHttpInfo(Login, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List/Search users
     * @param {module:model/RestSearchUserRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RestUsersCollection} and HTTP response
     */
    searchUsersWithHttpInfo(body) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling searchUsers");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RestUsersCollection;
      return this.apiClient.callApi(
        '/user', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List/Search users
     * @param {module:model/RestSearchUserRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RestUsersCollection}
     */
    searchUsers(body) {
      return this.searchUsersWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
